from steampipe_alchemy.models.aws_redshift_cluster import AwsRedshiftCluster
from steampipe_alchemy.models.aws_redshiftserverless_workgroup import AwsRedshiftserverlessWorkgroup
from steampipe_alchemy.models.aws_networkfirewall_firewall import AwsNetworkfirewallFirewall
from steampipe_alchemy.models.aws_ec2_reserved_instance import AwsEc2ReservedInstance
from steampipe_alchemy.models.aws_vpc_network_acl import AwsVpcNetworkAcl
from steampipe_alchemy.models.aws_identitystore_group import AwsIdentitystoreGroup
from steampipe_alchemy.models.aws_ssm_document import AwsSsmDocument
from steampipe_alchemy.models.aws_vpc_vpn_gateway import AwsVpcVpnGateway
from steampipe_alchemy.models.aws_wellarchitected_lens_review_improvement import AwsWellarchitectedLensReviewImprovement
from steampipe_alchemy.models.aws_wellarchitected_workload import AwsWellarchitectedWorkload
from steampipe_alchemy.models.aws_securityhub_finding import AwsSecurityhubFinding
from steampipe_alchemy.models.aws_rds_db_event_subscription import AwsRdsDbEventSubscription
from steampipe_alchemy.models.aws_ssm_maintenance_window import AwsSsmMaintenanceWindow
from steampipe_alchemy.models.aws_directory_service_log_subscription import AwsDirectoryServiceLogSubscription
from steampipe_alchemy.models.aws_codebuild_source_credential import AwsCodebuildSourceCredential
from steampipe_alchemy.models.aws_dax_subnet_group import AwsDaxSubnetGroup
from steampipe_alchemy.models.aws_macie2_classification_job import AwsMacie2ClassificationJob
from steampipe_alchemy.models.aws_cloudformation_stack_set import AwsCloudformationStackSet
from steampipe_alchemy.models.aws_eks_addon_version import AwsEksAddonVersion
from steampipe_alchemy.models.aws_guardduty_threat_intel_set import AwsGuarddutyThreatIntelSet
from steampipe_alchemy.models.aws_s3_object import AwsS3Object
from steampipe_alchemy.models.aws_directory_service_directory import AwsDirectoryServiceDirectory
from steampipe_alchemy.models.aws_ec2_managed_prefix_list import AwsEc2ManagedPrefixList
from steampipe_alchemy.models.aws_iam_open_id_connect_provider import AwsIamOpenIdConnectProvider
from steampipe_alchemy.models.aws_networkfirewall_firewall_policy import AwsNetworkfirewallFirewallPolicy
from steampipe_alchemy.models.aws_identitystore_group_membership import AwsIdentitystoreGroupMembership
from steampipe_alchemy.models.aws_dax_parameter_group import AwsDaxParameterGroup
from steampipe_alchemy.models.aws_wellarchitected_answer import AwsWellarchitectedAnswer
from steampipe_alchemy.models.aws_wellarchitected_lens import AwsWellarchitectedLens
from steampipe_alchemy.models.aws_s3_access_point import AwsS3AccessPoint
from steampipe_alchemy.models.aws_guardduty_finding import AwsGuarddutyFinding
from steampipe_alchemy.models.aws_dms_replication_task import AwsDmsReplicationTask
from steampipe_alchemy.models.aws_sfn_state_machine import AwsSfnStateMachine
from steampipe_alchemy.models.aws_iam_policy_attachment import AwsIamPolicyAttachment
from steampipe_alchemy.models.aws_vpc_internet_gateway import AwsVpcInternetGateway
from steampipe_alchemy.models.aws_wafregional_rule import AwsWafregionalRule
from steampipe_alchemy.models.aws_efs_file_system import AwsEfsFileSystem
from steampipe_alchemy.models.aws_vpc_eip_address_transfer import AwsVpcEipAddressTransfer
from steampipe_alchemy.models.aws_efs_access_point import AwsEfsAccessPoint
from steampipe_alchemy.models.aws_elasticache_subnet_group import AwsElasticacheSubnetGroup
from steampipe_alchemy.models.aws_lambda_version import AwsLambdaVersion
from steampipe_alchemy.models.aws_ec2_capacity_reservation import AwsEc2CapacityReservation
from steampipe_alchemy.models.aws_emr_block_public_access_configuration import AwsEmrBlockPublicAccessConfiguration
from steampipe_alchemy.models.aws_cloudformation_stack import AwsCloudformationStack
from steampipe_alchemy.models.aws_cloudfront_origin_access_identity import AwsCloudfrontOriginAccessIdentity
from steampipe_alchemy.models.aws_codeartifact_repository import AwsCodeartifactRepository
from steampipe_alchemy.models.aws_route53_health_check import AwsRoute53HealthCheck
from steampipe_alchemy.models.aws_config_aggregate_authorization import AwsConfigAggregateAuthorization
from steampipe_alchemy.models.aws_organizations_root import AwsOrganizationsRoot
from steampipe_alchemy.models.aws_ecs_task_definition import AwsEcsTaskDefinition
from steampipe_alchemy.models.aws_vpc_route_table import AwsVpcRouteTable
from steampipe_alchemy.models.aws_auditmanager_evidence_folder import AwsAuditmanagerEvidenceFolder
from steampipe_alchemy.models.aws_codebuild_build import AwsCodebuildBuild
from steampipe_alchemy.models.aws_route53_query_log import AwsRoute53QueryLog
from steampipe_alchemy.models.aws_pinpoint_app import AwsPinpointApp
from steampipe_alchemy.models.aws_cloudtrail_lookup_event import AwsCloudtrailLookupEvent
from steampipe_alchemy.models.aws_docdb_cluster import AwsDocdbCluster
from steampipe_alchemy.models.aws_route53_traffic_policy_instance import AwsRoute53TrafficPolicyInstance
from steampipe_alchemy.models.aws_securityhub_standards_control import AwsSecurityhubStandardsControl
from steampipe_alchemy.models.aws_backup_recovery_point import AwsBackupRecoveryPoint
from steampipe_alchemy.models.aws_securitylake_subscriber import AwsSecuritylakeSubscriber
from steampipe_alchemy.models.aws_iam_policy import AwsIamPolicy
from steampipe_alchemy.models.aws_drs_job import AwsDrsJob
from steampipe_alchemy.models.aws_route53_domain import AwsRoute53Domain
from steampipe_alchemy.models.aws_ec2_ami import AwsEc2Ami
from steampipe_alchemy.models.aws_vpc_dhcp_options import AwsVpcDhcpOptions
from steampipe_alchemy.models.aws_ssm_inventory_entry import AwsSsmInventoryEntry
from steampipe_alchemy.models.aws_ecr_image import AwsEcrImage
from steampipe_alchemy.models.aws_api_gateway_usage_plan import AwsApiGatewayUsagePlan
from steampipe_alchemy.models.aws_auditmanager_control import AwsAuditmanagerControl
from steampipe_alchemy.models.aws_ec2_transit_gateway_route import AwsEc2TransitGatewayRoute
from steampipe_alchemy.models.aws_appconfig_application import AwsAppconfigApplication
from steampipe_alchemy.models.aws_ec2_network_interface import AwsEc2NetworkInterface
from steampipe_alchemy.models.aws_inspector_assessment_target import AwsInspectorAssessmentTarget
from steampipe_alchemy.models.aws_cloudwatch_log_group import AwsCloudwatchLogGroup
from steampipe_alchemy.models.aws_wellarchitected_lens_share import AwsWellarchitectedLensShare
from steampipe_alchemy.models.aws_elastic_beanstalk_application import AwsElasticBeanstalkApplication
from steampipe_alchemy.models.aws_codeartifact_domain import AwsCodeartifactDomain
from steampipe_alchemy.models.aws_ssoadmin_instance import AwsSsoadminInstance
from steampipe_alchemy.models.aws_iam_saml_provider import AwsIamSamlProvider
from steampipe_alchemy.models.aws_api_gateway_rest_api import AwsApiGatewayRestApi
from steampipe_alchemy.models.aws_iam_account_password_policy import AwsIamAccountPasswordPolicy
from steampipe_alchemy.models.aws_backup_framework import AwsBackupFramework
from steampipe_alchemy.models.aws_iot_thing_group import AwsIotThingGroup
from steampipe_alchemy.models.aws_inspector2_finding import AwsInspector2Finding
from steampipe_alchemy.models.aws_emr_instance_group import AwsEmrInstanceGroup
from steampipe_alchemy.models.aws_ssoadmin_permission_set import AwsSsoadminPermissionSet
from steampipe_alchemy.models.aws_workspaces_directory import AwsWorkspacesDirectory
from steampipe_alchemy.models.aws_rds_db_recommendation import AwsRdsDbRecommendation
from steampipe_alchemy.models.aws_s3_bucket import AwsS3Bucket
from steampipe_alchemy.models.aws_amplify_app import AwsAmplifyApp
from steampipe_alchemy.models.aws_rds_db_cluster_parameter_group import AwsRdsDbClusterParameterGroup
from steampipe_alchemy.models.aws_iam_action import AwsIamAction
from steampipe_alchemy.models.aws_api_gatewayv2_domain_name import AwsApiGatewayv2DomainName
from steampipe_alchemy.models.aws_service_discovery_namespace import AwsServiceDiscoveryNamespace
from steampipe_alchemy.models.aws_vpc_flow_log import AwsVpcFlowLog
from steampipe_alchemy.models.aws_sts_caller_identity import AwsStsCallerIdentity
from steampipe_alchemy.models.aws_eks_node_group import AwsEksNodeGroup
from steampipe_alchemy.models.aws_athena_query_execution import AwsAthenaQueryExecution
from steampipe_alchemy.models.aws_cognito_identity_pool import AwsCognitoIdentityPool
from steampipe_alchemy.models.aws_servicecatalog_portfolio import AwsServicecatalogPortfolio
from steampipe_alchemy.models.aws_efs_mount_target import AwsEfsMountTarget
from steampipe_alchemy.models.aws_athena_workgroup import AwsAthenaWorkgroup
from steampipe_alchemy.models.aws_guardduty_member import AwsGuarddutyMember
from steampipe_alchemy.models.aws_route53_zone import AwsRoute53Zone
from steampipe_alchemy.models.aws_ec2_managed_prefix_list_entry import AwsEc2ManagedPrefixListEntry
from steampipe_alchemy.models.aws_cognito_identity_provider import AwsCognitoIdentityProvider
from steampipe_alchemy.models.aws_cloudfront_origin_request_policy import AwsCloudfrontOriginRequestPolicy
from steampipe_alchemy.models.aws_redshiftserverless_namespace import AwsRedshiftserverlessNamespace
from steampipe_alchemy.models.aws_lambda_alias import AwsLambdaAlias
from steampipe_alchemy.models.aws_config_conformance_pack import AwsConfigConformancePack
from steampipe_alchemy.models.aws_inspector2_member import AwsInspector2Member
from steampipe_alchemy.models.aws_opensearch_domain import AwsOpensearchDomain
from steampipe_alchemy.models.aws_vpc_verified_access_instance import AwsVpcVerifiedAccessInstance
from steampipe_alchemy.models.aws_dms_replication_instance import AwsDmsReplicationInstance
from steampipe_alchemy.models.aws_sagemaker_notebook_instance import AwsSagemakerNotebookInstance
from steampipe_alchemy.models.aws_ec2_ami_shared import AwsEc2AmiShared
from steampipe_alchemy.models.aws_cloudwatch_log_subscription_filter import AwsCloudwatchLogSubscriptionFilter
from steampipe_alchemy.models.aws_eks_addon import AwsEksAddon
from steampipe_alchemy.models.aws_dax_parameter import AwsDaxParameter
from steampipe_alchemy.models.aws_cloudtrail_event_data_store import AwsCloudtrailEventDataStore
from steampipe_alchemy.models.aws_guardduty_ipset import AwsGuarddutyIpset
from steampipe_alchemy.models.aws_rds_db_subnet_group import AwsRdsDbSubnetGroup
from steampipe_alchemy.models.aws_kinesis_consumer import AwsKinesisConsumer
from steampipe_alchemy.models.aws_wellarchitected_check_summary import AwsWellarchitectedCheckSummary
from steampipe_alchemy.models.aws_docdb_cluster_instance import AwsDocdbClusterInstance
from steampipe_alchemy.models.aws_cloudwatch_log_event import AwsCloudwatchLogEvent
from steampipe_alchemy.models.aws_cloudtrail_trail import AwsCloudtrailTrail
from steampipe_alchemy.models.aws_ec2_classic_load_balancer import AwsEc2ClassicLoadBalancer
from steampipe_alchemy.models.aws_sfn_state_machine_execution_history import AwsSfnStateMachineExecutionHistory
from steampipe_alchemy.models.aws_codedeploy_deployment_group import AwsCodedeployDeploymentGroup
from steampipe_alchemy.models.aws_vpc_customer_gateway import AwsVpcCustomerGateway
from steampipe_alchemy.models.aws_emr_cluster import AwsEmrCluster
from steampipe_alchemy.models.aws_cloudtrail_channel import AwsCloudtrailChannel
from steampipe_alchemy.models.aws_ec2_ssl_policy import AwsEc2SslPolicy
from steampipe_alchemy.models.aws_servicecatalog_provisioned_product import AwsServicecatalogProvisionedProduct
from steampipe_alchemy.models.aws_wellarchitected_lens_review import AwsWellarchitectedLensReview
from steampipe_alchemy.models.aws_securityhub_finding_aggregator import AwsSecurityhubFindingAggregator
from steampipe_alchemy.models.aws_waf_rule_group import AwsWafRuleGroup
from steampipe_alchemy.models.aws_backup_job import AwsBackupJob
from steampipe_alchemy.models.aws_resource_explorer_search import AwsResourceExplorerSearch
from steampipe_alchemy.models.aws_route53_record import AwsRoute53Record
from steampipe_alchemy.models.aws_ssmincidents_response_plan import AwsSsmincidentsResponsePlan
from steampipe_alchemy.models.aws_eks_fargate_profile import AwsEksFargateProfile
from steampipe_alchemy.models.aws_cloudsearch_domain import AwsCloudsearchDomain
from steampipe_alchemy.models.aws_ssm_association import AwsSsmAssociation
from steampipe_alchemy.models.aws_ec2_instance_availability import AwsEc2InstanceAvailability
from steampipe_alchemy.models.aws_sns_subscription import AwsSnsSubscription
from steampipe_alchemy.models.aws_auditmanager_evidence import AwsAuditmanagerEvidence
from steampipe_alchemy.models.aws_acm_certificate import AwsAcmCertificate
from steampipe_alchemy.models.aws_emr_instance_fleet import AwsEmrInstanceFleet
from steampipe_alchemy.models.aws_ec2_transit_gateway import AwsEc2TransitGateway
from steampipe_alchemy.models.aws_drs_source_server import AwsDrsSourceServer
from steampipe_alchemy.models.aws_glue_catalog_database import AwsGlueCatalogDatabase
from steampipe_alchemy.models.aws_iot_thing_type import AwsIotThingType
from steampipe_alchemy.models.aws_drs_recovery_instance import AwsDrsRecoveryInstance
from steampipe_alchemy.models.aws_ec2_instance_type import AwsEc2InstanceType
from steampipe_alchemy.models.aws_inspector_finding import AwsInspectorFinding
from steampipe_alchemy.models.aws_backup_vault import AwsBackupVault
from steampipe_alchemy.models.aws_servicecatalog_product import AwsServicecatalogProduct
from steampipe_alchemy.models.aws_s3_multi_region_access_point import AwsS3MultiRegionAccessPoint
from steampipe_alchemy.models.aws_waf_rule import AwsWafRule
from steampipe_alchemy.models.aws_ses_email_identity import AwsSesEmailIdentity
from steampipe_alchemy.models.aws_ebs_snapshot import AwsEbsSnapshot
from steampipe_alchemy.models.aws_backup_legal_hold import AwsBackupLegalHold
from steampipe_alchemy.models.aws_cloudwatch_log_stream import AwsCloudwatchLogStream
from steampipe_alchemy.models.aws_msk_serverless_cluster import AwsMskServerlessCluster
from steampipe_alchemy.models.aws_organizations_organizational_unit import AwsOrganizationsOrganizationalUnit
from steampipe_alchemy.models.aws_iam_server_certificate import AwsIamServerCertificate
from steampipe_alchemy.models.aws_ec2_instance import AwsEc2Instance
from steampipe_alchemy.models.aws_ec2_network_load_balancer import AwsEc2NetworkLoadBalancer
from steampipe_alchemy.models.aws_dlm_lifecycle_policy import AwsDlmLifecyclePolicy
from steampipe_alchemy.models.aws_ecs_cluster import AwsEcsCluster
from steampipe_alchemy.models.aws_rds_db_proxy import AwsRdsDbProxy
from steampipe_alchemy.models.aws_cloudtrail_query import AwsCloudtrailQuery
from steampipe_alchemy.models.aws_route53_resolver_endpoint import AwsRoute53ResolverEndpoint
from steampipe_alchemy.models.aws_vpc_security_group_rule import AwsVpcSecurityGroupRule
from steampipe_alchemy.models.aws_iot_fleet_metric import AwsIotFleetMetric
from steampipe_alchemy.models.aws_sfn_state_machine_execution import AwsSfnStateMachineExecution
from steampipe_alchemy.models.aws_rds_db_engine_version import AwsRdsDbEngineVersion
from steampipe_alchemy.models.aws_waf_rate_based_rule import AwsWafRateBasedRule
from steampipe_alchemy.models.aws_pipes_pipe import AwsPipesPipe
from steampipe_alchemy.models.aws_media_store_container import AwsMediaStoreContainer
from steampipe_alchemy.models.aws_dms_certificate import AwsDmsCertificate
from steampipe_alchemy.models.aws_account import AwsAccount
from steampipe_alchemy.models.aws_rds_db_snapshot import AwsRdsDbSnapshot
from steampipe_alchemy.models.aws_rds_db_parameter_group import AwsRdsDbParameterGroup
from steampipe_alchemy.models.aws_iam_user import AwsIamUser
from steampipe_alchemy.models.aws_ssm_inventory import AwsSsmInventory
from steampipe_alchemy.models.aws_iam_role import AwsIamRole
from steampipe_alchemy.models.aws_ec2_launch_configuration import AwsEc2LaunchConfiguration
from steampipe_alchemy.models.aws_accessanalyzer_finding import AwsAccessanalyzerFinding
from steampipe_alchemy.models.aws_cloudfront_distribution import AwsCloudfrontDistribution
from steampipe_alchemy.models.aws_glue_catalog_table import AwsGlueCatalogTable
from steampipe_alchemy.models.aws_docdb_cluster_snapshot import AwsDocdbClusterSnapshot
from steampipe_alchemy.models.aws_s3_account_settings import AwsS3AccountSettings
from steampipe_alchemy.models.aws_cognito_user_pool import AwsCognitoUserPool
from steampipe_alchemy.models.aws_workspaces_workspace import AwsWorkspacesWorkspace
from steampipe_alchemy.models.aws_servicequotas_service import AwsServicequotasService
from steampipe_alchemy.models.aws_ec2_transit_gateway_vpc_attachment import AwsEc2TransitGatewayVpcAttachment
from steampipe_alchemy.models.aws_api_gatewayv2_api import AwsApiGatewayv2Api
from steampipe_alchemy.models.aws_rds_db_instance_automated_backup import AwsRdsDbInstanceAutomatedBackup
from steampipe_alchemy.models.aws_kinesisanalyticsv2_application import AwsKinesisanalyticsv2Application
from steampipe_alchemy.models.aws_identitystore_user import AwsIdentitystoreUser
from steampipe_alchemy.models.aws_securityhub_insight import AwsSecurityhubInsight
from steampipe_alchemy.models.aws_auditmanager_framework import AwsAuditmanagerFramework
from steampipe_alchemy.models.aws_ec2_client_vpn_endpoint import AwsEc2ClientVpnEndpoint
from steampipe_alchemy.models.aws_elasticache_parameter_group import AwsElasticacheParameterGroup
from steampipe_alchemy.models.aws_ec2_target_group import AwsEc2TargetGroup
from steampipe_alchemy.models.aws_globalaccelerator_listener import AwsGlobalacceleratorListener
from steampipe_alchemy.models.aws_config_rule import AwsConfigRule
from steampipe_alchemy.models.aws_elastic_beanstalk_environment import AwsElasticBeanstalkEnvironment
from steampipe_alchemy.models.aws_wafv2_ip_set import AwsWafv2IpSet
from steampipe_alchemy.models.aws_securityhub_member import AwsSecurityhubMember
from steampipe_alchemy.models.aws_glue_security_configuration import AwsGlueSecurityConfiguration
from steampipe_alchemy.models.aws_cloudwatch_alarm import AwsCloudwatchAlarm
from steampipe_alchemy.models.aws_codepipeline_pipeline import AwsCodepipelinePipeline
from steampipe_alchemy.models.aws_iam_access_advisor import AwsIamAccessAdvisor
from steampipe_alchemy.models.aws_api_gateway_stage import AwsApiGatewayStage
from steampipe_alchemy.models.aws_serverlessapplicationrepository_application import AwsServerlessapplicationrepositoryApplication
from steampipe_alchemy.models.aws_kinesis_firehose_delivery_stream import AwsKinesisFirehoseDeliveryStream
from steampipe_alchemy.models.aws_vpc_endpoint import AwsVpcEndpoint
from steampipe_alchemy.models.aws_servicequotas_service_quota import AwsServicequotasServiceQuota
from steampipe_alchemy.models.aws_auditmanager_assessment import AwsAuditmanagerAssessment
from steampipe_alchemy.models.aws_securityhub_hub import AwsSecurityhubHub
from steampipe_alchemy.models.aws_ebs_volume import AwsEbsVolume
from steampipe_alchemy.models.aws_guardduty_detector import AwsGuarddutyDetector
from steampipe_alchemy.models.aws_wafv2_rule_group import AwsWafv2RuleGroup
from steampipe_alchemy.models.aws_servicequotas_default_service_quota import AwsServicequotasDefaultServiceQuota
from steampipe_alchemy.models.aws_rds_db_option_group import AwsRdsDbOptionGroup
from steampipe_alchemy.models.aws_wafv2_regex_pattern_set import AwsWafv2RegexPatternSet
from steampipe_alchemy.models.aws_vpc_verified_access_group import AwsVpcVerifiedAccessGroup
from steampipe_alchemy.models.aws_guardduty_filter import AwsGuarddutyFilter
from steampipe_alchemy.models.aws_ram_resource_association import AwsRamResourceAssociation
from steampipe_alchemy.models.aws_emr_security_configuration import AwsEmrSecurityConfiguration
from steampipe_alchemy.models.aws_iam_access_key import AwsIamAccessKey
from steampipe_alchemy.models.aws_inspector_exclusion import AwsInspectorExclusion
from steampipe_alchemy.models.aws_wafregional_web_acl import AwsWafregionalWebAcl
from steampipe_alchemy.models.aws_organizations_policy import AwsOrganizationsPolicy
from steampipe_alchemy.models.aws_config_configuration_recorder import AwsConfigConfigurationRecorder
from steampipe_alchemy.models.aws_codedeploy_deployment_config import AwsCodedeployDeploymentConfig
from steampipe_alchemy.models.aws_elasticache_reserved_cache_node import AwsElasticacheReservedCacheNode
from steampipe_alchemy.models.aws_dynamodb_global_table import AwsDynamodbGlobalTable
from steampipe_alchemy.models.aws_oam_sink import AwsOamSink
from steampipe_alchemy.models.aws_lightsail_instance import AwsLightsailInstance
from steampipe_alchemy.models.aws_sagemaker_domain import AwsSagemakerDomain
from steampipe_alchemy.models.aws_api_gatewayv2_integration import AwsApiGatewayv2Integration
from steampipe_alchemy.models.aws_cloudformation_stack_resource import AwsCloudformationStackResource
from steampipe_alchemy.models.aws_service_discovery_service import AwsServiceDiscoveryService
from steampipe_alchemy.models.aws_redshift_subnet_group import AwsRedshiftSubnetGroup
from steampipe_alchemy.models.aws_securityhub_action_target import AwsSecurityhubActionTarget
from steampipe_alchemy.models.aws_ec2_launch_template_version import AwsEc2LaunchTemplateVersion
from steampipe_alchemy.models.aws_accessanalyzer_analyzer import AwsAccessanalyzerAnalyzer
from steampipe_alchemy.models.aws_route53_vpc_association_authorization import AwsRoute53VpcAssociationAuthorization
from steampipe_alchemy.models.aws_cloudtrail_import import AwsCloudtrailImport
from steampipe_alchemy.models.aws_glue_crawler import AwsGlueCrawler
from steampipe_alchemy.models.aws_oam_link import AwsOamLink
from steampipe_alchemy.models.aws_cloudfront_response_headers_policy import AwsCloudfrontResponseHeadersPolicy
from steampipe_alchemy.models.aws_ssm_managed_instance import AwsSsmManagedInstance
from steampipe_alchemy.models.aws_ec2_application_load_balancer import AwsEc2ApplicationLoadBalancer
from steampipe_alchemy.models.aws_sagemaker_training_job import AwsSagemakerTrainingJob
from steampipe_alchemy.models.aws_inspector2_coverage import AwsInspector2Coverage
from steampipe_alchemy.models.aws_glacier_vault import AwsGlacierVault
from steampipe_alchemy.models.aws_vpc_eip import AwsVpcEip
from steampipe_alchemy.models.aws_ssm_patch_baseline import AwsSsmPatchBaseline
from steampipe_alchemy.models.aws_acmpca_certificate_authority import AwsAcmpcaCertificateAuthority
from steampipe_alchemy.models.aws_cloudtrail_trail_event import AwsCloudtrailTrailEvent
from steampipe_alchemy.models.aws_appsync_graphql_api import AwsAppsyncGraphqlApi
from steampipe_alchemy.models.aws_vpc_egress_only_internet_gateway import AwsVpcEgressOnlyInternetGateway
from steampipe_alchemy.models.aws_cloudfront_cache_policy import AwsCloudfrontCachePolicy
from steampipe_alchemy.models.aws_resource_explorer_index import AwsResourceExplorerIndex
from steampipe_alchemy.models.aws_organizations_policy_target import AwsOrganizationsPolicyTarget
from steampipe_alchemy.models.aws_eks_identity_provider_config import AwsEksIdentityProviderConfig
from steampipe_alchemy.models.aws_backup_plan import AwsBackupPlan
from steampipe_alchemy.models.aws_redshift_event_subscription import AwsRedshiftEventSubscription
from steampipe_alchemy.models.aws_sns_topic import AwsSnsTopic
from steampipe_alchemy.models.aws_elasticsearch_domain import AwsElasticsearchDomain
from steampipe_alchemy.models.aws_redshift_parameter_group import AwsRedshiftParameterGroup
from steampipe_alchemy.models.aws_s3_object_version import AwsS3ObjectVersion
from steampipe_alchemy.models.aws_ssoadmin_managed_policy_attachment import AwsSsoadminManagedPolicyAttachment
from steampipe_alchemy.models.aws_iam_virtual_mfa_device import AwsIamVirtualMfaDevice
from steampipe_alchemy.models.aws_service_discovery_instance import AwsServiceDiscoveryInstance
from steampipe_alchemy.models.aws_iam_account_summary import AwsIamAccountSummary
from steampipe_alchemy.models.aws_vpc import AwsVpc
from steampipe_alchemy.models.aws_route53_traffic_policy import AwsRoute53TrafficPolicy
from steampipe_alchemy.models.aws_secretsmanager_secret import AwsSecretsmanagerSecret
from steampipe_alchemy.models.aws_globalaccelerator_endpoint_group import AwsGlobalacceleratorEndpointGroup
from steampipe_alchemy.models.aws_neptune_db_cluster_snapshot import AwsNeptuneDbClusterSnapshot
from steampipe_alchemy.models.aws_trusted_advisor_check_summary import AwsTrustedAdvisorCheckSummary
from steampipe_alchemy.models.aws_ecs_task import AwsEcsTask
from steampipe_alchemy.models.aws_ses_domain_identity import AwsSesDomainIdentity
from steampipe_alchemy.models.aws_ecr_image_scan_finding import AwsEcrImageScanFinding
from steampipe_alchemy.models.aws_directory_service_certificate import AwsDirectoryServiceCertificate
from steampipe_alchemy.models.aws_kms_key_rotation import AwsKmsKeyRotation
from steampipe_alchemy.models.aws_sagemaker_endpoint_configuration import AwsSagemakerEndpointConfiguration
from steampipe_alchemy.models.aws_route53_resolver_query_log_config import AwsRoute53ResolverQueryLogConfig
from steampipe_alchemy.models.aws_ec2_load_balancer_listener import AwsEc2LoadBalancerListener
from steampipe_alchemy.models.aws_route53_resolver_rule import AwsRoute53ResolverRule
from steampipe_alchemy.models.aws_codebuild_project import AwsCodebuildProject
from steampipe_alchemy.models.aws_sns_topic_subscription import AwsSnsTopicSubscription
from steampipe_alchemy.models.aws_networkfirewall_rule_group import AwsNetworkfirewallRuleGroup
from steampipe_alchemy.models.aws_api_gatewayv2_route import AwsApiGatewayv2Route
from steampipe_alchemy.models.aws_api_gateway_domain_name import AwsApiGatewayDomainName
from steampipe_alchemy.models.aws_ssm_parameter import AwsSsmParameter
from steampipe_alchemy.models.aws_cloudfront_function import AwsCloudfrontFunction
from steampipe_alchemy.models.aws_iam_service_specific_credential import AwsIamServiceSpecificCredential
from steampipe_alchemy.models.aws_elasticache_cluster import AwsElasticacheCluster
from steampipe_alchemy.models.aws_health_affected_entity import AwsHealthAffectedEntity
from steampipe_alchemy.models.aws_elastic_beanstalk_application_version import AwsElasticBeanstalkApplicationVersion
from steampipe_alchemy.models.aws_ec2_autoscaling_group import AwsEc2AutoscalingGroup
from steampipe_alchemy.models.aws_vpc_peering_connection import AwsVpcPeeringConnection
from steampipe_alchemy.models.aws_ecs_container_instance import AwsEcsContainerInstance
from steampipe_alchemy.models.aws_iot_thing import AwsIotThing
from steampipe_alchemy.models.aws_securityhub_product import AwsSecurityhubProduct
from steampipe_alchemy.models.aws_drs_recovery_snapshot import AwsDrsRecoverySnapshot
from steampipe_alchemy.models.aws_codedeploy_app import AwsCodedeployApp
from steampipe_alchemy.models.aws_codecommit_repository import AwsCodecommitRepository
from steampipe_alchemy.models.aws_transfer_server import AwsTransferServer
from steampipe_alchemy.models.aws_fsx_file_system import AwsFsxFileSystem
from steampipe_alchemy.models.aws_kinesis_video_stream import AwsKinesisVideoStream
from steampipe_alchemy.models.aws_appstream_image import AwsAppstreamImage
from steampipe_alchemy.models.aws_securitylake_data_lake import AwsSecuritylakeDataLake
from steampipe_alchemy.models.aws_backup_selection import AwsBackupSelection
from steampipe_alchemy.models.aws_vpc_vpn_connection import AwsVpcVpnConnection
from steampipe_alchemy.models.aws_ecr_registry_scanning_configuration import AwsEcrRegistryScanningConfiguration
from steampipe_alchemy.models.aws_api_gateway_authorizer import AwsApiGatewayAuthorizer
from steampipe_alchemy.models.aws_region import AwsRegion
from steampipe_alchemy.models.aws_fms_policy import AwsFmsPolicy
from steampipe_alchemy.models.aws_inspector_assessment_template import AwsInspectorAssessmentTemplate
from steampipe_alchemy.models.aws_api_gatewayv2_stage import AwsApiGatewayv2Stage
from steampipe_alchemy.models.aws_appstream_fleet import AwsAppstreamFleet
from steampipe_alchemy.models.aws_dynamodb_backup import AwsDynamodbBackup
from steampipe_alchemy.models.aws_ecs_service import AwsEcsService
from steampipe_alchemy.models.aws_emr_instance import AwsEmrInstance
from steampipe_alchemy.models.aws_redshift_snapshot import AwsRedshiftSnapshot
from steampipe_alchemy.models.aws_simspaceweaver_simulation import AwsSimspaceweaverSimulation
from steampipe_alchemy.models.aws_backup_protected_resource import AwsBackupProtectedResource
from steampipe_alchemy.models.aws_wellarchitected_workload_share import AwsWellarchitectedWorkloadShare
from steampipe_alchemy.models.aws_api_gateway_method import AwsApiGatewayMethod
from steampipe_alchemy.models.aws_servicequotas_service_quota_change_request import AwsServicequotasServiceQuotaChangeRequest
from steampipe_alchemy.models.aws_appautoscaling_target import AwsAppautoscalingTarget
from steampipe_alchemy.models.aws_ec2_regional_settings import AwsEc2RegionalSettings
from steampipe_alchemy.models.aws_cloudwatch_metric import AwsCloudwatchMetric
from steampipe_alchemy.models.aws_vpc_subnet import AwsVpcSubnet
from steampipe_alchemy.models.aws_sqs_queue import AwsSqsQueue
from steampipe_alchemy.models.aws_appautoscaling_policy import AwsAppautoscalingPolicy
from steampipe_alchemy.models.aws_ram_principal_association import AwsRamPrincipalAssociation
from steampipe_alchemy.models.aws_glue_dev_endpoint import AwsGlueDevEndpoint
from steampipe_alchemy.models.aws_ec2_key_pair import AwsEc2KeyPair
from steampipe_alchemy.models.aws_kms_alias import AwsKmsAlias
from steampipe_alchemy.models.aws_elasticache_replication_group import AwsElasticacheReplicationGroup
from steampipe_alchemy.models.aws_vpc_nat_gateway import AwsVpcNatGateway
from steampipe_alchemy.models.aws_ssm_document_permission import AwsSsmDocumentPermission
from steampipe_alchemy.models.aws_lambda_layer_version import AwsLambdaLayerVersion
from steampipe_alchemy.models.aws_lambda_function import AwsLambdaFunction
from steampipe_alchemy.models.aws_glue_job import AwsGlueJob
from steampipe_alchemy.models.aws_config_retention_configuration import AwsConfigRetentionConfiguration
from steampipe_alchemy.models.aws_wellarchitected_share_invitation import AwsWellarchitectedShareInvitation
from steampipe_alchemy.models.aws_dms_endpoint import AwsDmsEndpoint
from steampipe_alchemy.models.aws_rds_db_instance import AwsRdsDbInstance
from steampipe_alchemy.models.aws_health_event import AwsHealthEvent
from steampipe_alchemy.models.aws_cloudwatch_log_resource_policy import AwsCloudwatchLogResourcePolicy
from steampipe_alchemy.models.aws_sagemaker_app import AwsSagemakerApp
from steampipe_alchemy.models.aws_api_gateway_api_key import AwsApiGatewayApiKey
from steampipe_alchemy.models.aws_wafregional_rule_group import AwsWafregionalRuleGroup
from steampipe_alchemy.models.aws_vpc_verified_access_endpoint import AwsVpcVerifiedAccessEndpoint
from steampipe_alchemy.models.aws_availability_zone import AwsAvailabilityZone
from steampipe_alchemy.models.aws_mgn_application import AwsMgnApplication
from steampipe_alchemy.models.aws_msk_cluster import AwsMskCluster
from steampipe_alchemy.models.aws_kms_key import AwsKmsKey
from steampipe_alchemy.models.aws_ec2_launch_template import AwsEc2LaunchTemplate
from steampipe_alchemy.models.aws_fms_app_list import AwsFmsAppList
from steampipe_alchemy.models.aws_eks_cluster import AwsEksCluster
from steampipe_alchemy.models.aws_tagging_resource import AwsTaggingResource
from steampipe_alchemy.models.aws_ssm_managed_instance_compliance import AwsSsmManagedInstanceCompliance
from steampipe_alchemy.models.aws_vpc_route import AwsVpcRoute
from steampipe_alchemy.models.aws_dynamodb_table_export import AwsDynamodbTableExport
from steampipe_alchemy.models.aws_neptune_db_cluster import AwsNeptuneDbCluster
from steampipe_alchemy.models.aws_iam_group import AwsIamGroup
from steampipe_alchemy.models.aws_globalaccelerator_accelerator import AwsGlobalacceleratorAccelerator
from steampipe_alchemy.models.aws_wafv2_web_acl import AwsWafv2WebAcl
from steampipe_alchemy.models.aws_transfer_user import AwsTransferUser
from steampipe_alchemy.models.aws_vpc_verified_access_trust_provider import AwsVpcVerifiedAccessTrustProvider
from steampipe_alchemy.models.aws_rds_reserved_db_instance import AwsRdsReservedDbInstance
from steampipe_alchemy.models.aws_ec2_transit_gateway_route_table import AwsEc2TransitGatewayRouteTable
from steampipe_alchemy.models.aws_organizations_account import AwsOrganizationsAccount
from steampipe_alchemy.models.aws_ecrpublic_repository import AwsEcrpublicRepository
from steampipe_alchemy.models.aws_dynamodb_table import AwsDynamodbTable
from steampipe_alchemy.models.aws_inspector_assessment_run import AwsInspectorAssessmentRun
from steampipe_alchemy.models.aws_rds_db_cluster_snapshot import AwsRdsDbClusterSnapshot
from steampipe_alchemy.models.aws_s3_bucket_intelligent_tiering_configuration import AwsS3BucketIntelligentTieringConfiguration
from steampipe_alchemy.models.aws_ecr_repository import AwsEcrRepository
from steampipe_alchemy.models.aws_guardduty_publishing_destination import AwsGuarddutyPublishingDestination
from steampipe_alchemy.models.aws_account_alternate_contact import AwsAccountAlternateContact
from steampipe_alchemy.models.aws_iam_policy_simulator import AwsIamPolicySimulator
from steampipe_alchemy.models.aws_kinesis_stream import AwsKinesisStream
from steampipe_alchemy.models.aws_eventbridge_rule import AwsEventbridgeRule
from steampipe_alchemy.models.aws_eventbridge_bus import AwsEventbridgeBus
from steampipe_alchemy.models.aws_sagemaker_model import AwsSagemakerModel
from steampipe_alchemy.models.aws_account_contact import AwsAccountContact
from steampipe_alchemy.models.aws_wellarchitected_check_detail import AwsWellarchitectedCheckDetail
from steampipe_alchemy.models.aws_glue_connection import AwsGlueConnection
from steampipe_alchemy.models.aws_mq_broker import AwsMqBroker
from steampipe_alchemy.models.aws_waf_web_acl import AwsWafWebAcl
from steampipe_alchemy.models.aws_glue_data_quality_ruleset import AwsGlueDataQualityRuleset
from steampipe_alchemy.models.aws_securityhub_standards_subscription import AwsSecurityhubStandardsSubscription
from steampipe_alchemy.models.aws_ssm_managed_instance_patch_state import AwsSsmManagedInstancePatchState
from steampipe_alchemy.models.aws_lambda_event_source_mapping import AwsLambdaEventSourceMapping
from steampipe_alchemy.models.aws_lambda_layer import AwsLambdaLayer
from steampipe_alchemy.models.aws_ec2_gateway_load_balancer import AwsEc2GatewayLoadBalancer
from steampipe_alchemy.models.aws_vpc_security_group import AwsVpcSecurityGroup
from steampipe_alchemy.models.aws_vpc_endpoint_service import AwsVpcEndpointService
from steampipe_alchemy.models.aws_dax_cluster import AwsDaxCluster
from steampipe_alchemy.models.aws_rds_db_cluster import AwsRdsDbCluster


all = {
  "RedshiftCluster": AwsRedshiftCluster,
  "RedshiftserverlessWorkgroup": AwsRedshiftserverlessWorkgroup,
  "NetworkfirewallFirewall": AwsNetworkfirewallFirewall,
  "Ec2ReservedInstance": AwsEc2ReservedInstance,
  "VpcNetworkAcl": AwsVpcNetworkAcl,
  "IdentitystoreGroup": AwsIdentitystoreGroup,
  "SsmDocument": AwsSsmDocument,
  "VpcVpnGateway": AwsVpcVpnGateway,
  "WellarchitectedLensReviewImprovement": AwsWellarchitectedLensReviewImprovement,
  "WellarchitectedWorkload": AwsWellarchitectedWorkload,
  "SecurityhubFinding": AwsSecurityhubFinding,
  "RdsDbEventSubscription": AwsRdsDbEventSubscription,
  "SsmMaintenanceWindow": AwsSsmMaintenanceWindow,
  "DirectoryServiceLogSubscription": AwsDirectoryServiceLogSubscription,
  "CodebuildSourceCredential": AwsCodebuildSourceCredential,
  "DaxSubnetGroup": AwsDaxSubnetGroup,
  "Macie2ClassificationJob": AwsMacie2ClassificationJob,
  "CloudformationStackSet": AwsCloudformationStackSet,
  "EksAddonVersion": AwsEksAddonVersion,
  "GuarddutyThreatIntelSet": AwsGuarddutyThreatIntelSet,
  "S3Object": AwsS3Object,
  "DirectoryServiceDirectory": AwsDirectoryServiceDirectory,
  "Ec2ManagedPrefixList": AwsEc2ManagedPrefixList,
  "IamOpenIdConnectProvider": AwsIamOpenIdConnectProvider,
  "NetworkfirewallFirewallPolicy": AwsNetworkfirewallFirewallPolicy,
  "IdentitystoreGroupMembership": AwsIdentitystoreGroupMembership,
  "DaxParameterGroup": AwsDaxParameterGroup,
  "WellarchitectedAnswer": AwsWellarchitectedAnswer,
  "WellarchitectedLens": AwsWellarchitectedLens,
  "S3AccessPoint": AwsS3AccessPoint,
  "GuarddutyFinding": AwsGuarddutyFinding,
  "DmsReplicationTask": AwsDmsReplicationTask,
  "SfnStateMachine": AwsSfnStateMachine,
  "IamPolicyAttachment": AwsIamPolicyAttachment,
  "VpcInternetGateway": AwsVpcInternetGateway,
  "WafregionalRule": AwsWafregionalRule,
  "EfsFileSystem": AwsEfsFileSystem,
  "VpcEipAddressTransfer": AwsVpcEipAddressTransfer,
  "EfsAccessPoint": AwsEfsAccessPoint,
  "ElasticacheSubnetGroup": AwsElasticacheSubnetGroup,
  "LambdaVersion": AwsLambdaVersion,
  "Ec2CapacityReservation": AwsEc2CapacityReservation,
  "EmrBlockPublicAccessConfiguration": AwsEmrBlockPublicAccessConfiguration,
  "CloudformationStack": AwsCloudformationStack,
  "CloudfrontOriginAccessIdentity": AwsCloudfrontOriginAccessIdentity,
  "CodeartifactRepository": AwsCodeartifactRepository,
  "Route53HealthCheck": AwsRoute53HealthCheck,
  "ConfigAggregateAuthorization": AwsConfigAggregateAuthorization,
  "OrganizationsRoot": AwsOrganizationsRoot,
  "EcsTaskDefinition": AwsEcsTaskDefinition,
  "VpcRouteTable": AwsVpcRouteTable,
  "AuditmanagerEvidenceFolder": AwsAuditmanagerEvidenceFolder,
  "CodebuildBuild": AwsCodebuildBuild,
  "Route53QueryLog": AwsRoute53QueryLog,
  "PinpointApp": AwsPinpointApp,
  "CloudtrailLookupEvent": AwsCloudtrailLookupEvent,
  "DocdbCluster": AwsDocdbCluster,
  "Route53TrafficPolicyInstance": AwsRoute53TrafficPolicyInstance,
  "SecurityhubStandardsControl": AwsSecurityhubStandardsControl,
  "BackupRecoveryPoint": AwsBackupRecoveryPoint,
  "SecuritylakeSubscriber": AwsSecuritylakeSubscriber,
  "IamPolicy": AwsIamPolicy,
  "DrsJob": AwsDrsJob,
  "Route53Domain": AwsRoute53Domain,
  "Ec2Ami": AwsEc2Ami,
  "VpcDhcpOptions": AwsVpcDhcpOptions,
  "SsmInventoryEntry": AwsSsmInventoryEntry,
  "EcrImage": AwsEcrImage,
  "ApiGatewayUsagePlan": AwsApiGatewayUsagePlan,
  "AuditmanagerControl": AwsAuditmanagerControl,
  "Ec2TransitGatewayRoute": AwsEc2TransitGatewayRoute,
  "AppconfigApplication": AwsAppconfigApplication,
  "Ec2NetworkInterface": AwsEc2NetworkInterface,
  "InspectorAssessmentTarget": AwsInspectorAssessmentTarget,
  "CloudwatchLogGroup": AwsCloudwatchLogGroup,
  "WellarchitectedLensShare": AwsWellarchitectedLensShare,
  "ElasticBeanstalkApplication": AwsElasticBeanstalkApplication,
  "CodeartifactDomain": AwsCodeartifactDomain,
  "SsoadminInstance": AwsSsoadminInstance,
  "IamSamlProvider": AwsIamSamlProvider,
  "ApiGatewayRestApi": AwsApiGatewayRestApi,
  "IamAccountPasswordPolicy": AwsIamAccountPasswordPolicy,
  "BackupFramework": AwsBackupFramework,
  "IotThingGroup": AwsIotThingGroup,
  "Inspector2Finding": AwsInspector2Finding,
  "EmrInstanceGroup": AwsEmrInstanceGroup,
  "SsoadminPermissionSet": AwsSsoadminPermissionSet,
  "WorkspacesDirectory": AwsWorkspacesDirectory,
  "RdsDbRecommendation": AwsRdsDbRecommendation,
  "S3Bucket": AwsS3Bucket,
  "AmplifyApp": AwsAmplifyApp,
  "RdsDbClusterParameterGroup": AwsRdsDbClusterParameterGroup,
  "IamAction": AwsIamAction,
  "ApiGatewayv2DomainName": AwsApiGatewayv2DomainName,
  "ServiceDiscoveryNamespace": AwsServiceDiscoveryNamespace,
  "VpcFlowLog": AwsVpcFlowLog,
  "StsCallerIdentity": AwsStsCallerIdentity,
  "EksNodeGroup": AwsEksNodeGroup,
  "AthenaQueryExecution": AwsAthenaQueryExecution,
  "CognitoIdentityPool": AwsCognitoIdentityPool,
  "ServicecatalogPortfolio": AwsServicecatalogPortfolio,
  "EfsMountTarget": AwsEfsMountTarget,
  "AthenaWorkgroup": AwsAthenaWorkgroup,
  "GuarddutyMember": AwsGuarddutyMember,
  "Route53Zone": AwsRoute53Zone,
  "Ec2ManagedPrefixListEntry": AwsEc2ManagedPrefixListEntry,
  "CognitoIdentityProvider": AwsCognitoIdentityProvider,
  "CloudfrontOriginRequestPolicy": AwsCloudfrontOriginRequestPolicy,
  "RedshiftserverlessNamespace": AwsRedshiftserverlessNamespace,
  "LambdaAlias": AwsLambdaAlias,
  "ConfigConformancePack": AwsConfigConformancePack,
  "Inspector2Member": AwsInspector2Member,
  "OpensearchDomain": AwsOpensearchDomain,
  "VpcVerifiedAccessInstance": AwsVpcVerifiedAccessInstance,
  "DmsReplicationInstance": AwsDmsReplicationInstance,
  "SagemakerNotebookInstance": AwsSagemakerNotebookInstance,
  "Ec2AmiShared": AwsEc2AmiShared,
  "CloudwatchLogSubscriptionFilter": AwsCloudwatchLogSubscriptionFilter,
  "EksAddon": AwsEksAddon,
  "DaxParameter": AwsDaxParameter,
  "CloudtrailEventDataStore": AwsCloudtrailEventDataStore,
  "GuarddutyIpset": AwsGuarddutyIpset,
  "RdsDbSubnetGroup": AwsRdsDbSubnetGroup,
  "KinesisConsumer": AwsKinesisConsumer,
  "WellarchitectedCheckSummary": AwsWellarchitectedCheckSummary,
  "DocdbClusterInstance": AwsDocdbClusterInstance,
  "CloudwatchLogEvent": AwsCloudwatchLogEvent,
  "CloudtrailTrail": AwsCloudtrailTrail,
  "Ec2ClassicLoadBalancer": AwsEc2ClassicLoadBalancer,
  "SfnStateMachineExecutionHistory": AwsSfnStateMachineExecutionHistory,
  "CodedeployDeploymentGroup": AwsCodedeployDeploymentGroup,
  "VpcCustomerGateway": AwsVpcCustomerGateway,
  "EmrCluster": AwsEmrCluster,
  "CloudtrailChannel": AwsCloudtrailChannel,
  "Ec2SslPolicy": AwsEc2SslPolicy,
  "ServicecatalogProvisionedProduct": AwsServicecatalogProvisionedProduct,
  "WellarchitectedLensReview": AwsWellarchitectedLensReview,
  "SecurityhubFindingAggregator": AwsSecurityhubFindingAggregator,
  "WafRuleGroup": AwsWafRuleGroup,
  "BackupJob": AwsBackupJob,
  "ResourceExplorerSearch": AwsResourceExplorerSearch,
  "Route53Record": AwsRoute53Record,
  "SsmincidentsResponsePlan": AwsSsmincidentsResponsePlan,
  "EksFargateProfile": AwsEksFargateProfile,
  "CloudsearchDomain": AwsCloudsearchDomain,
  "SsmAssociation": AwsSsmAssociation,
  "Ec2InstanceAvailability": AwsEc2InstanceAvailability,
  "SnsSubscription": AwsSnsSubscription,
  "AuditmanagerEvidence": AwsAuditmanagerEvidence,
  "AcmCertificate": AwsAcmCertificate,
  "EmrInstanceFleet": AwsEmrInstanceFleet,
  "Ec2TransitGateway": AwsEc2TransitGateway,
  "DrsSourceServer": AwsDrsSourceServer,
  "GlueCatalogDatabase": AwsGlueCatalogDatabase,
  "IotThingType": AwsIotThingType,
  "DrsRecoveryInstance": AwsDrsRecoveryInstance,
  "Ec2InstanceType": AwsEc2InstanceType,
  "InspectorFinding": AwsInspectorFinding,
  "BackupVault": AwsBackupVault,
  "ServicecatalogProduct": AwsServicecatalogProduct,
  "S3MultiRegionAccessPoint": AwsS3MultiRegionAccessPoint,
  "WafRule": AwsWafRule,
  "SesEmailIdentity": AwsSesEmailIdentity,
  "EbsSnapshot": AwsEbsSnapshot,
  "BackupLegalHold": AwsBackupLegalHold,
  "CloudwatchLogStream": AwsCloudwatchLogStream,
  "MskServerlessCluster": AwsMskServerlessCluster,
  "OrganizationsOrganizationalUnit": AwsOrganizationsOrganizationalUnit,
  "IamServerCertificate": AwsIamServerCertificate,
  "Ec2Instance": AwsEc2Instance,
  "Ec2NetworkLoadBalancer": AwsEc2NetworkLoadBalancer,
  "DlmLifecyclePolicy": AwsDlmLifecyclePolicy,
  "EcsCluster": AwsEcsCluster,
  "RdsDbProxy": AwsRdsDbProxy,
  "CloudtrailQuery": AwsCloudtrailQuery,
  "Route53ResolverEndpoint": AwsRoute53ResolverEndpoint,
  "VpcSecurityGroupRule": AwsVpcSecurityGroupRule,
  "IotFleetMetric": AwsIotFleetMetric,
  "SfnStateMachineExecution": AwsSfnStateMachineExecution,
  "RdsDbEngineVersion": AwsRdsDbEngineVersion,
  "WafRateBasedRule": AwsWafRateBasedRule,
  "PipesPipe": AwsPipesPipe,
  "MediaStoreContainer": AwsMediaStoreContainer,
  "DmsCertificate": AwsDmsCertificate,
  "Account": AwsAccount,
  "RdsDbSnapshot": AwsRdsDbSnapshot,
  "RdsDbParameterGroup": AwsRdsDbParameterGroup,
  "IamUser": AwsIamUser,
  "SsmInventory": AwsSsmInventory,
  "IamRole": AwsIamRole,
  "Ec2LaunchConfiguration": AwsEc2LaunchConfiguration,
  "AccessanalyzerFinding": AwsAccessanalyzerFinding,
  "CloudfrontDistribution": AwsCloudfrontDistribution,
  "GlueCatalogTable": AwsGlueCatalogTable,
  "DocdbClusterSnapshot": AwsDocdbClusterSnapshot,
  "S3AccountSettings": AwsS3AccountSettings,
  "CognitoUserPool": AwsCognitoUserPool,
  "WorkspacesWorkspace": AwsWorkspacesWorkspace,
  "ServicequotasService": AwsServicequotasService,
  "Ec2TransitGatewayVpcAttachment": AwsEc2TransitGatewayVpcAttachment,
  "ApiGatewayv2Api": AwsApiGatewayv2Api,
  "RdsDbInstanceAutomatedBackup": AwsRdsDbInstanceAutomatedBackup,
  "Kinesisanalyticsv2Application": AwsKinesisanalyticsv2Application,
  "IdentitystoreUser": AwsIdentitystoreUser,
  "SecurityhubInsight": AwsSecurityhubInsight,
  "AuditmanagerFramework": AwsAuditmanagerFramework,
  "Ec2ClientVpnEndpoint": AwsEc2ClientVpnEndpoint,
  "ElasticacheParameterGroup": AwsElasticacheParameterGroup,
  "Ec2TargetGroup": AwsEc2TargetGroup,
  "GlobalacceleratorListener": AwsGlobalacceleratorListener,
  "ConfigRule": AwsConfigRule,
  "ElasticBeanstalkEnvironment": AwsElasticBeanstalkEnvironment,
  "Wafv2IpSet": AwsWafv2IpSet,
  "SecurityhubMember": AwsSecurityhubMember,
  "GlueSecurityConfiguration": AwsGlueSecurityConfiguration,
  "CloudwatchAlarm": AwsCloudwatchAlarm,
  "CodepipelinePipeline": AwsCodepipelinePipeline,
  "IamAccessAdvisor": AwsIamAccessAdvisor,
  "ApiGatewayStage": AwsApiGatewayStage,
  "ServerlessapplicationrepositoryApplication": AwsServerlessapplicationrepositoryApplication,
  "KinesisFirehoseDeliveryStream": AwsKinesisFirehoseDeliveryStream,
  "VpcEndpoint": AwsVpcEndpoint,
  "ServicequotasServiceQuota": AwsServicequotasServiceQuota,
  "AuditmanagerAssessment": AwsAuditmanagerAssessment,
  "SecurityhubHub": AwsSecurityhubHub,
  "EbsVolume": AwsEbsVolume,
  "GuarddutyDetector": AwsGuarddutyDetector,
  "Wafv2RuleGroup": AwsWafv2RuleGroup,
  "ServicequotasDefaultServiceQuota": AwsServicequotasDefaultServiceQuota,
  "RdsDbOptionGroup": AwsRdsDbOptionGroup,
  "Wafv2RegexPatternSet": AwsWafv2RegexPatternSet,
  "VpcVerifiedAccessGroup": AwsVpcVerifiedAccessGroup,
  "GuarddutyFilter": AwsGuarddutyFilter,
  "RamResourceAssociation": AwsRamResourceAssociation,
  "EmrSecurityConfiguration": AwsEmrSecurityConfiguration,
  "IamAccessKey": AwsIamAccessKey,
  "InspectorExclusion": AwsInspectorExclusion,
  "WafregionalWebAcl": AwsWafregionalWebAcl,
  "OrganizationsPolicy": AwsOrganizationsPolicy,
  "ConfigConfigurationRecorder": AwsConfigConfigurationRecorder,
  "CodedeployDeploymentConfig": AwsCodedeployDeploymentConfig,
  "ElasticacheReservedCacheNode": AwsElasticacheReservedCacheNode,
  "DynamodbGlobalTable": AwsDynamodbGlobalTable,
  "OamSink": AwsOamSink,
  "LightsailInstance": AwsLightsailInstance,
  "SagemakerDomain": AwsSagemakerDomain,
  "ApiGatewayv2Integration": AwsApiGatewayv2Integration,
  "CloudformationStackResource": AwsCloudformationStackResource,
  "ServiceDiscoveryService": AwsServiceDiscoveryService,
  "RedshiftSubnetGroup": AwsRedshiftSubnetGroup,
  "SecurityhubActionTarget": AwsSecurityhubActionTarget,
  "Ec2LaunchTemplateVersion": AwsEc2LaunchTemplateVersion,
  "AccessanalyzerAnalyzer": AwsAccessanalyzerAnalyzer,
  "Route53VpcAssociationAuthorization": AwsRoute53VpcAssociationAuthorization,
  "CloudtrailImport": AwsCloudtrailImport,
  "GlueCrawler": AwsGlueCrawler,
  "OamLink": AwsOamLink,
  "CloudfrontResponseHeadersPolicy": AwsCloudfrontResponseHeadersPolicy,
  "SsmManagedInstance": AwsSsmManagedInstance,
  "Ec2ApplicationLoadBalancer": AwsEc2ApplicationLoadBalancer,
  "SagemakerTrainingJob": AwsSagemakerTrainingJob,
  "Inspector2Coverage": AwsInspector2Coverage,
  "GlacierVault": AwsGlacierVault,
  "VpcEip": AwsVpcEip,
  "SsmPatchBaseline": AwsSsmPatchBaseline,
  "AcmpcaCertificateAuthority": AwsAcmpcaCertificateAuthority,
  "CloudtrailTrailEvent": AwsCloudtrailTrailEvent,
  "AppsyncGraphqlApi": AwsAppsyncGraphqlApi,
  "VpcEgressOnlyInternetGateway": AwsVpcEgressOnlyInternetGateway,
  "CloudfrontCachePolicy": AwsCloudfrontCachePolicy,
  "ResourceExplorerIndex": AwsResourceExplorerIndex,
  "OrganizationsPolicyTarget": AwsOrganizationsPolicyTarget,
  "EksIdentityProviderConfig": AwsEksIdentityProviderConfig,
  "BackupPlan": AwsBackupPlan,
  "RedshiftEventSubscription": AwsRedshiftEventSubscription,
  "SnsTopic": AwsSnsTopic,
  "ElasticsearchDomain": AwsElasticsearchDomain,
  "RedshiftParameterGroup": AwsRedshiftParameterGroup,
  "S3ObjectVersion": AwsS3ObjectVersion,
  "SsoadminManagedPolicyAttachment": AwsSsoadminManagedPolicyAttachment,
  "IamVirtualMfaDevice": AwsIamVirtualMfaDevice,
  "ServiceDiscoveryInstance": AwsServiceDiscoveryInstance,
  "IamAccountSummary": AwsIamAccountSummary,
  "Vpc": AwsVpc,
  "Route53TrafficPolicy": AwsRoute53TrafficPolicy,
  "SecretsmanagerSecret": AwsSecretsmanagerSecret,
  "GlobalacceleratorEndpointGroup": AwsGlobalacceleratorEndpointGroup,
  "NeptuneDbClusterSnapshot": AwsNeptuneDbClusterSnapshot,
  "TrustedAdvisorCheckSummary": AwsTrustedAdvisorCheckSummary,
  "EcsTask": AwsEcsTask,
  "SesDomainIdentity": AwsSesDomainIdentity,
  "EcrImageScanFinding": AwsEcrImageScanFinding,
  "DirectoryServiceCertificate": AwsDirectoryServiceCertificate,
  "KmsKeyRotation": AwsKmsKeyRotation,
  "SagemakerEndpointConfiguration": AwsSagemakerEndpointConfiguration,
  "Route53ResolverQueryLogConfig": AwsRoute53ResolverQueryLogConfig,
  "Ec2LoadBalancerListener": AwsEc2LoadBalancerListener,
  "Route53ResolverRule": AwsRoute53ResolverRule,
  "CodebuildProject": AwsCodebuildProject,
  "SnsTopicSubscription": AwsSnsTopicSubscription,
  "NetworkfirewallRuleGroup": AwsNetworkfirewallRuleGroup,
  "ApiGatewayv2Route": AwsApiGatewayv2Route,
  "ApiGatewayDomainName": AwsApiGatewayDomainName,
  "SsmParameter": AwsSsmParameter,
  "CloudfrontFunction": AwsCloudfrontFunction,
  "IamServiceSpecificCredential": AwsIamServiceSpecificCredential,
  "ElasticacheCluster": AwsElasticacheCluster,
  "HealthAffectedEntity": AwsHealthAffectedEntity,
  "ElasticBeanstalkApplicationVersion": AwsElasticBeanstalkApplicationVersion,
  "Ec2AutoscalingGroup": AwsEc2AutoscalingGroup,
  "VpcPeeringConnection": AwsVpcPeeringConnection,
  "EcsContainerInstance": AwsEcsContainerInstance,
  "IotThing": AwsIotThing,
  "SecurityhubProduct": AwsSecurityhubProduct,
  "DrsRecoverySnapshot": AwsDrsRecoverySnapshot,
  "CodedeployApp": AwsCodedeployApp,
  "CodecommitRepository": AwsCodecommitRepository,
  "TransferServer": AwsTransferServer,
  "FsxFileSystem": AwsFsxFileSystem,
  "KinesisVideoStream": AwsKinesisVideoStream,
  "AppstreamImage": AwsAppstreamImage,
  "SecuritylakeDataLake": AwsSecuritylakeDataLake,
  "BackupSelection": AwsBackupSelection,
  "VpcVpnConnection": AwsVpcVpnConnection,
  "EcrRegistryScanningConfiguration": AwsEcrRegistryScanningConfiguration,
  "ApiGatewayAuthorizer": AwsApiGatewayAuthorizer,
  "Region": AwsRegion,
  "FmsPolicy": AwsFmsPolicy,
  "InspectorAssessmentTemplate": AwsInspectorAssessmentTemplate,
  "ApiGatewayv2Stage": AwsApiGatewayv2Stage,
  "AppstreamFleet": AwsAppstreamFleet,
  "DynamodbBackup": AwsDynamodbBackup,
  "EcsService": AwsEcsService,
  "EmrInstance": AwsEmrInstance,
  "RedshiftSnapshot": AwsRedshiftSnapshot,
  "SimspaceweaverSimulation": AwsSimspaceweaverSimulation,
  "BackupProtectedResource": AwsBackupProtectedResource,
  "WellarchitectedWorkloadShare": AwsWellarchitectedWorkloadShare,
  "ApiGatewayMethod": AwsApiGatewayMethod,
  "ServicequotasServiceQuotaChangeRequest": AwsServicequotasServiceQuotaChangeRequest,
  "AppautoscalingTarget": AwsAppautoscalingTarget,
  "Ec2RegionalSettings": AwsEc2RegionalSettings,
  "CloudwatchMetric": AwsCloudwatchMetric,
  "VpcSubnet": AwsVpcSubnet,
  "SqsQueue": AwsSqsQueue,
  "AppautoscalingPolicy": AwsAppautoscalingPolicy,
  "RamPrincipalAssociation": AwsRamPrincipalAssociation,
  "GlueDevEndpoint": AwsGlueDevEndpoint,
  "Ec2KeyPair": AwsEc2KeyPair,
  "KmsAlias": AwsKmsAlias,
  "ElasticacheReplicationGroup": AwsElasticacheReplicationGroup,
  "VpcNatGateway": AwsVpcNatGateway,
  "SsmDocumentPermission": AwsSsmDocumentPermission,
  "LambdaLayerVersion": AwsLambdaLayerVersion,
  "LambdaFunction": AwsLambdaFunction,
  "GlueJob": AwsGlueJob,
  "ConfigRetentionConfiguration": AwsConfigRetentionConfiguration,
  "WellarchitectedShareInvitation": AwsWellarchitectedShareInvitation,
  "DmsEndpoint": AwsDmsEndpoint,
  "RdsDbInstance": AwsRdsDbInstance,
  "HealthEvent": AwsHealthEvent,
  "CloudwatchLogResourcePolicy": AwsCloudwatchLogResourcePolicy,
  "SagemakerApp": AwsSagemakerApp,
  "ApiGatewayApiKey": AwsApiGatewayApiKey,
  "WafregionalRuleGroup": AwsWafregionalRuleGroup,
  "VpcVerifiedAccessEndpoint": AwsVpcVerifiedAccessEndpoint,
  "AvailabilityZone": AwsAvailabilityZone,
  "MgnApplication": AwsMgnApplication,
  "MskCluster": AwsMskCluster,
  "KmsKey": AwsKmsKey,
  "Ec2LaunchTemplate": AwsEc2LaunchTemplate,
  "FmsAppList": AwsFmsAppList,
  "EksCluster": AwsEksCluster,
  "TaggingResource": AwsTaggingResource,
  "SsmManagedInstanceCompliance": AwsSsmManagedInstanceCompliance,
  "VpcRoute": AwsVpcRoute,
  "DynamodbTableExport": AwsDynamodbTableExport,
  "NeptuneDbCluster": AwsNeptuneDbCluster,
  "IamGroup": AwsIamGroup,
  "GlobalacceleratorAccelerator": AwsGlobalacceleratorAccelerator,
  "Wafv2WebAcl": AwsWafv2WebAcl,
  "TransferUser": AwsTransferUser,
  "VpcVerifiedAccessTrustProvider": AwsVpcVerifiedAccessTrustProvider,
  "RdsReservedDbInstance": AwsRdsReservedDbInstance,
  "Ec2TransitGatewayRouteTable": AwsEc2TransitGatewayRouteTable,
  "OrganizationsAccount": AwsOrganizationsAccount,
  "EcrpublicRepository": AwsEcrpublicRepository,
  "DynamodbTable": AwsDynamodbTable,
  "InspectorAssessmentRun": AwsInspectorAssessmentRun,
  "RdsDbClusterSnapshot": AwsRdsDbClusterSnapshot,
  "S3BucketIntelligentTieringConfiguration": AwsS3BucketIntelligentTieringConfiguration,
  "EcrRepository": AwsEcrRepository,
  "GuarddutyPublishingDestination": AwsGuarddutyPublishingDestination,
  "AccountAlternateContact": AwsAccountAlternateContact,
  "IamPolicySimulator": AwsIamPolicySimulator,
  "KinesisStream": AwsKinesisStream,
  "EventbridgeRule": AwsEventbridgeRule,
  "EventbridgeBus": AwsEventbridgeBus,
  "SagemakerModel": AwsSagemakerModel,
  "AccountContact": AwsAccountContact,
  "WellarchitectedCheckDetail": AwsWellarchitectedCheckDetail,
  "GlueConnection": AwsGlueConnection,
  "MqBroker": AwsMqBroker,
  "WafWebAcl": AwsWafWebAcl,
  "GlueDataQualityRuleset": AwsGlueDataQualityRuleset,
  "SecurityhubStandardsSubscription": AwsSecurityhubStandardsSubscription,
  "SsmManagedInstancePatchState": AwsSsmManagedInstancePatchState,
  "LambdaEventSourceMapping": AwsLambdaEventSourceMapping,
  "LambdaLayer": AwsLambdaLayer,
  "Ec2GatewayLoadBalancer": AwsEc2GatewayLoadBalancer,
  "VpcSecurityGroup": AwsVpcSecurityGroup,
  "VpcEndpointService": AwsVpcEndpointService,
  "DaxCluster": AwsDaxCluster,
  "RdsDbCluster": AwsRdsDbCluster
}
