from sqlalchemy import Column
from sqlalchemy.types import JSON, Text, Boolean, TIMESTAMP, BigInteger
from sqlalchemy.dialects import postgresql as psql
from steampipe_alchemy.mixins import FormatMixins

from steampipe_alchemy import Base

class AwsInspector2Finding(Base, FormatMixins):
    __tablename__ = 'aws_inspector2_finding'
    cvss = Column('cvss', JSON, nullable=True)
    first_observed_at = Column('first_observed_at', TIMESTAMP, nullable=True)
    inspector_score = Column('inspector_score', psql.DOUBLE_PRECISION, nullable=True)
    ecr_image_pushed_at = Column('ecr_image_pushed_at', TIMESTAMP, nullable=True)
    lambda_function_last_modified_at = Column('lambda_function_last_modified_at', TIMESTAMP, nullable=True)
    last_observed_at = Column('last_observed_at', TIMESTAMP, nullable=True)
    updated_at = Column('updated_at', TIMESTAMP, nullable=True)
    vendor_created_at = Column('vendor_created_at', TIMESTAMP, nullable=True)
    vendor_updated_at = Column('vendor_updated_at', TIMESTAMP, nullable=True)
    exploitability_details = Column('exploitability_details', JSON, nullable=True)
    inspector_score_details = Column('inspector_score_details', JSON, nullable=True)
    network_reachability_details = Column('network_reachability_details', JSON, nullable=True)
    package_vulnerability_details = Column('package_vulnerability_details', JSON, nullable=True)
    reference_urls = Column('reference_urls', JSON, nullable=True)
    related_vulnerabilities = Column('related_vulnerabilities', JSON, nullable=True)
    vulnerable_package = Column('vulnerable_package', JSON, nullable=True)
    vulnerable_packages = Column('vulnerable_packages', JSON, nullable=True)
    resources = Column('resources', JSON, nullable=True)
    resource_tags = Column('resource_tags', JSON, nullable=True)
    akas = Column('akas', JSON, nullable=True)
    sp_ctx = Column('sp_ctx', JSON, nullable=True)
    _ctx = Column('_ctx', JSON, nullable=True)
    lambda_function_execution_role_arn = Column('lambda_function_execution_role_arn', Text, nullable=True)
    sp_connection_name = Column('sp_connection_name', Text, nullable=True)
    lambda_function_layers = Column('lambda_function_layers', Text, nullable=True)
    lambda_function_name = Column('lambda_function_name', Text, nullable=True)
    lambda_function_runtime = Column('lambda_function_runtime', Text, nullable=True)
    network_protocol = Column('network_protocol', Text, nullable=True)
    related_vulnerabilitie = Column('related_vulnerabilitie', Text, nullable=True)
    partition = Column('partition', Text, nullable=True)
    remediation_recommendation_text = Column('remediation_recommendation_text', Text, nullable=True)
    remediation_recommendation_url = Column('remediation_recommendation_url', Text, nullable=True)
    severity = Column('severity', Text, nullable=True)
    region = Column('region', Text, nullable=True)
    source = Column('source', Text, nullable=True)
    source_url = Column('source_url', Text, nullable=True)
    finding_account_id = Column('finding_account_id', Text, nullable=True)
    vendor_severity = Column('vendor_severity', Text, nullable=True)
    description = Column('description', Text, nullable=True)
    exploit_available = Column('exploit_available', Text, nullable=True)
    arn = Column('arn', Text, primary_key=True, nullable=True)
    status = Column('status', Text, nullable=True)
    type = Column('type', Text, nullable=True)
    account_id = Column('account_id', Text, nullable=True)
    fix_available = Column('fix_available', Text, nullable=True)
    vulnerability_id = Column('vulnerability_id', Text, nullable=True)
    resource_id = Column('resource_id', Text, nullable=True)
    resource_type = Column('resource_type', Text, nullable=True)
    component_type = Column('component_type', Text, nullable=True)
    component_id = Column('component_id', Text, nullable=True)
    ec2_instance_image_id = Column('ec2_instance_image_id', Text, nullable=True)
    ec2_instance_subnet_id = Column('ec2_instance_subnet_id', Text, nullable=True)
    ec2_instance_vpc_id = Column('ec2_instance_vpc_id', Text, nullable=True)
    ecr_image_architecture = Column('ecr_image_architecture', Text, nullable=True)
    ecr_image_hash = Column('ecr_image_hash', Text, nullable=True)
    title = Column('title', Text, nullable=True)
    ecr_image_registry = Column('ecr_image_registry', Text, nullable=True)
    ecr_image_repository_name = Column('ecr_image_repository_name', Text, nullable=True)
    ecr_image_tags = Column('ecr_image_tags', Text, nullable=True)