from sqlalchemy import Column
from sqlalchemy.types import JSON, Text, Boolean, TIMESTAMP, BigInteger
from sqlalchemy.dialects import postgresql as psql
from steampipe_alchemy.mixins import FormatMixins

from steampipe_alchemy import Base

class AwsSagemakerTrainingJob(Base, FormatMixins):
    __tablename__ = 'aws_sagemaker_training_job'
    _ctx = Column('_ctx', JSON, nullable=True)
    input_data_config = Column('input_data_config', JSON, nullable=True)
    model_artifacts = Column('model_artifacts', JSON, nullable=True)
    output_data_config = Column('output_data_config', JSON, nullable=True)
    profiler_config = Column('profiler_config', JSON, nullable=True)
    profiler_rule_configurations = Column('profiler_rule_configurations', JSON, nullable=True)
    profiler_rule_evaluation_statuses = Column('profiler_rule_evaluation_statuses', JSON, nullable=True)
    resource_config = Column('resource_config', JSON, nullable=True)
    secondary_status_transitions = Column('secondary_status_transitions', JSON, nullable=True)
    stopping_condition = Column('stopping_condition', JSON, nullable=True)
    tensor_board_output_config = Column('tensor_board_output_config', JSON, nullable=True)
    vpc_config = Column('vpc_config', JSON, nullable=True)
    tags_src = Column('tags_src', JSON, nullable=True)
    tags = Column('tags', JSON, nullable=True)
    akas = Column('akas', JSON, nullable=True)
    sp_ctx = Column('sp_ctx', JSON, nullable=True)
    billable_time_in_seconds = Column('billable_time_in_seconds', BigInteger, nullable=True)
    creation_time = Column('creation_time', TIMESTAMP, nullable=True)
    enable_managed_spot_training = Column('enable_managed_spot_training', Boolean, nullable=True)
    enable_network_isolation = Column('enable_network_isolation', Boolean, nullable=True)
    enable_inter_container_traffic_encryption = Column('enable_inter_container_traffic_encryption', Boolean, nullable=True)
    last_modified_time = Column('last_modified_time', TIMESTAMP, nullable=True)
    training_end_time = Column('training_end_time', TIMESTAMP, nullable=True)
    training_start_time = Column('training_start_time', TIMESTAMP, nullable=True)
    training_time_in_seconds = Column('training_time_in_seconds', BigInteger, nullable=True)
    algorithm_specification = Column('algorithm_specification', JSON, nullable=True)
    checkpoint_config = Column('checkpoint_config', JSON, nullable=True)
    debug_hook_config = Column('debug_hook_config', JSON, nullable=True)
    debug_rule_configurations = Column('debug_rule_configurations', JSON, nullable=True)
    debug_rule_evaluation_statuses = Column('debug_rule_evaluation_statuses', JSON, nullable=True)
    environment = Column('environment', JSON, nullable=True)
    experiment_config = Column('experiment_config', JSON, nullable=True)
    final_metric_data_list = Column('final_metric_data_list', JSON, nullable=True)
    hyper_parameters = Column('hyper_parameters', JSON, nullable=True)
    arn = Column('arn', Text, primary_key=True, nullable=True)
    training_job_status = Column('training_job_status', Text, nullable=True)
    auto_ml_job_arn = Column('auto_ml_job_arn', Text, nullable=True)
    sp_connection_name = Column('sp_connection_name', Text, nullable=True)
    name = Column('name', Text, nullable=True)
    tuning_job_arn = Column('tuning_job_arn', Text, nullable=True)
    partition = Column('partition', Text, nullable=True)
    region = Column('region', Text, nullable=True)
    failure_reason = Column('failure_reason', Text, nullable=True)
    labeling_job_arn = Column('labeling_job_arn', Text, nullable=True)
    account_id = Column('account_id', Text, nullable=True)
    profiling_status = Column('profiling_status', Text, nullable=True)
    role_arn = Column('role_arn', Text, nullable=True)
    secondary_status = Column('secondary_status', Text, nullable=True)
    title = Column('title', Text, nullable=True)