from sqlalchemy import Column
from sqlalchemy.types import JSON, Text, Boolean, TIMESTAMP, BigInteger
from sqlalchemy.dialects import postgresql as psql
from steampipe_alchemy.mixins import FormatMixins

from steampipe_alchemy import Base

class AwsSecurityhubFinding(Base, FormatMixins):
    __tablename__ = 'aws_securityhub_finding'
    threat_intel_indicators = Column('threat_intel_indicators', JSON, nullable=True)
    criticality = Column('criticality', BigInteger, nullable=True)
    first_observed_at = Column('first_observed_at', TIMESTAMP, nullable=True)
    last_observed_at = Column('last_observed_at', TIMESTAMP, nullable=True)
    action = Column('action', JSON, nullable=True)
    compliance = Column('compliance', JSON, nullable=True)
    finding_provider_fields = Column('finding_provider_fields', JSON, nullable=True)
    malware = Column('malware', JSON, nullable=True)
    network = Column('network', JSON, nullable=True)
    network_path = Column('network_path', JSON, nullable=True)
    note = Column('note', JSON, nullable=True)
    patch_summary = Column('patch_summary', JSON, nullable=True)
    process = Column('process', JSON, nullable=True)
    product_fields = Column('product_fields', JSON, nullable=True)
    related_findings = Column('related_findings', JSON, nullable=True)
    remediation = Column('remediation', JSON, nullable=True)
    resources = Column('resources', JSON, nullable=True)
    severity = Column('severity', JSON, nullable=True)
    user_defined_fields = Column('user_defined_fields', JSON, nullable=True)
    vulnerabilities = Column('vulnerabilities', JSON, nullable=True)
    sp_ctx = Column('sp_ctx', JSON, nullable=True)
    _ctx = Column('_ctx', JSON, nullable=True)
    confidence = Column('confidence', BigInteger, nullable=True)
    created_at = Column('created_at', TIMESTAMP, nullable=True)
    updated_at = Column('updated_at', TIMESTAMP, nullable=True)
    arn = Column('arn', Text, primary_key=True, nullable=True)
    company_name = Column('company_name', Text, nullable=True)
    account_id = Column('account_id', Text, nullable=True)
    sp_connection_name = Column('sp_connection_name', Text, nullable=True)
    compliance_status = Column('compliance_status', Text, nullable=True)
    source_account_id = Column('source_account_id', Text, nullable=True)
    title = Column('title', Text, nullable=True)
    description = Column('description', Text, nullable=True)
    partition = Column('partition', Text, nullable=True)
    generator_id = Column('generator_id', Text, nullable=True)
    region = Column('region', Text, nullable=True)
    product_arn = Column('product_arn', Text, nullable=True)
    product_name = Column('product_name', Text, nullable=True)
    record_state = Column('record_state', Text, nullable=True)
    schema_version = Column('schema_version', Text, nullable=True)
    source_url = Column('source_url', Text, nullable=True)
    verification_state = Column('verification_state', Text, nullable=True)
    workflow_state = Column('workflow_state', Text, nullable=True)
    workflow_status = Column('workflow_status', Text, nullable=True)
    standards_control_arn = Column('standards_control_arn', Text, nullable=True)
    id = Column('id', Text, nullable=True)