from sqlalchemy import Column
from sqlalchemy.types import JSON, Text, Boolean, TIMESTAMP, BigInteger
from sqlalchemy.dialects import postgresql as psql

from steampipe_alchemy.base import Base

class AwsRedshiftCluster(Base):
    __tablename__ = 'aws_redshift_cluster'
    cluster_identifier = Column(Text, name='cluster_identifier', nullable=True)
    cluster_namespace_arn = Column(Text, name='cluster_namespace_arn', nullable=True)
    allow_version_upgrade = Column(Boolean, name='allow_version_upgrade', nullable=True)
    automated_snapshot_retention_period = Column(BigInteger, name='automated_snapshot_retention_period', nullable=True)
    availability_zone = Column(Text, name='availability_zone', nullable=True)
    availability_zone_relocation_status = Column(Text, name='availability_zone_relocation_status', nullable=True)
    cluster_availability_status = Column(Text, name='cluster_availability_status', nullable=True)
    cluster_create_time = Column(TIMESTAMP, name='cluster_create_time', nullable=True)
    cluster_nodes = Column(JSON, name='cluster_nodes', nullable=True)
    cluster_parameter_groups = Column(JSON, name='cluster_parameter_groups', nullable=True)
    cluster_public_key = Column(Text, name='cluster_public_key', nullable=True)
    cluster_revision_number = Column(Text, name='cluster_revision_number', nullable=True)
    cluster_security_groups = Column(JSON, name='cluster_security_groups', nullable=True)
    cluster_snapshot_copy_status = Column(JSON, name='cluster_snapshot_copy_status', nullable=True)
    cluster_status = Column(Text, name='cluster_status', nullable=True)
    cluster_subnet_group_name = Column(Text, name='cluster_subnet_group_name', nullable=True)
    cluster_version = Column(Text, name='cluster_version', nullable=True)
    data_transfer_progress = Column(JSON, name='data_transfer_progress', nullable=True)
    db_name = Column(Text, name='db_name', nullable=True)
    deferred_maintenance_windows = Column(JSON, name='deferred_maintenance_windows', nullable=True)
    elastic_ip_status = Column(JSON, name='elastic_ip_status', nullable=True)
    elastic_resize_number_of_node_options = Column(Text, name='elastic_resize_number_of_node_options', nullable=True)
    encrypted = Column(Boolean, name='encrypted', nullable=True)
    endpoint = Column(JSON, name='endpoint', nullable=True)
    enhanced_vpc_routing = Column(Boolean, name='enhanced_vpc_routing', nullable=True)
    expected_next_snapshot_schedule_time = Column(TIMESTAMP, name='expected_next_snapshot_schedule_time', nullable=True)
    expected_next_snapshot_schedule_time_status = Column(Text, name='expected_next_snapshot_schedule_time_status', nullable=True)
    hsm_status = Column(JSON, name='hsm_status', nullable=True)
    iam_roles = Column(JSON, name='iam_roles', nullable=True)
    kms_key_id = Column(Text, name='kms_key_id', nullable=True)
    maintenance_track_name = Column(Text, name='maintenance_track_name', nullable=True)
    manual_snapshot_retention_period = Column(BigInteger, name='manual_snapshot_retention_period', nullable=True)
    master_username = Column(Text, name='master_username', nullable=True)
    modify_status = Column(Text, name='modify_status', nullable=True)
    next_maintenance_window_start_time = Column(TIMESTAMP, name='next_maintenance_window_start_time', nullable=True)
    node_type = Column(Text, name='node_type', nullable=True)
    number_of_nodes = Column(BigInteger, name='number_of_nodes', nullable=True)
    pending_actions = Column(JSON, name='pending_actions', nullable=True)
    pending_modified_values = Column(JSON, name='pending_modified_values', nullable=True)
    preferred_maintenance_window = Column(Text, name='preferred_maintenance_window', nullable=True)
    publicly_accessible = Column(Boolean, name='publicly_accessible', nullable=True)
    resize_info = Column(JSON, name='resize_info', nullable=True)
    restore_status = Column(JSON, name='restore_status', nullable=True)
    snapshot_schedule_identifier = Column(Text, name='snapshot_schedule_identifier', nullable=True)
    snapshot_schedule_state = Column(Text, name='snapshot_schedule_state', nullable=True)
    tags_src = Column(JSON, name='tags_src', nullable=True)
    vpc_id = Column(Text, name='vpc_id', nullable=True)
    vpc_security_groups = Column(JSON, name='vpc_security_groups', nullable=True)
    tags = Column(JSON, name='tags', nullable=True)
    title = Column(Text, name='title', primary_key=True, nullable=True)
    akas = Column(JSON, name='akas', nullable=True)
    partition = Column(Text, name='partition', nullable=True)
    region = Column(Text, name='region', nullable=True)
    account_id = Column(Text, name='account_id', nullable=True)