from sqlalchemy import Column
from sqlalchemy.types import JSON, Text, Boolean, TIMESTAMP, BigInteger
from sqlalchemy.dialects import postgresql as psql
from steampipe_alchemy.mixins import FormatMixins

from steampipe_alchemy import Base

class AwsDmsEndpoint(Base, FormatMixins):
    __tablename__ = 'aws_dms_endpoint'
    sybase_settings = Column('sybase_settings', JSON, nullable=True)
    doc_db_settings = Column('doc_db_settings', JSON, nullable=True)
    dynamo_db_settings = Column('dynamo_db_settings', JSON, nullable=True)
    elasticsearch_settings = Column('elasticsearch_settings', JSON, nullable=True)
    gcp_my_sql_settings = Column('gcp_my_sql_settings', JSON, nullable=True)
    ibm_db2_settings = Column('ibm_db2_settings', JSON, nullable=True)
    kafka_settings = Column('kafka_settings', JSON, nullable=True)
    kinesis_settings = Column('kinesis_settings', JSON, nullable=True)
    microsoft_sql_server_settings = Column('microsoft_sql_server_settings', JSON, nullable=True)
    mongo_db_settings = Column('mongo_db_settings', JSON, nullable=True)
    my_sql_settings = Column('my_sql_settings', JSON, nullable=True)
    neptune_settings = Column('neptune_settings', JSON, nullable=True)
    oracle_settings = Column('oracle_settings', JSON, nullable=True)
    postgre_sql_settings = Column('postgre_sql_settings', JSON, nullable=True)
    redis_settings = Column('redis_settings', JSON, nullable=True)
    redshift_settings = Column('redshift_settings', JSON, nullable=True)
    s3_settings = Column('s3_settings', JSON, nullable=True)
    tags_src = Column('tags_src', JSON, nullable=True)
    tags = Column('tags', JSON, nullable=True)
    akas = Column('akas', JSON, nullable=True)
    sp_ctx = Column('sp_ctx', JSON, nullable=True)
    _ctx = Column('_ctx', JSON, nullable=True)
    port = Column('port', BigInteger, nullable=True)
    dms_transfer_settings = Column('dms_transfer_settings', JSON, nullable=True)
    arn = Column('arn', Text, primary_key=True, nullable=True)
    certificate_arn = Column('certificate_arn', Text, nullable=True)
    database_name = Column('database_name', Text, nullable=True)
    endpoint_type = Column('endpoint_type', Text, nullable=True)
    engine_display_name = Column('engine_display_name', Text, nullable=True)
    engine_name = Column('engine_name', Text, nullable=True)
    external_id = Column('external_id', Text, nullable=True)
    external_table_definition = Column('external_table_definition', Text, nullable=True)
    extra_connection_attributes = Column('extra_connection_attributes', Text, nullable=True)
    kms_key_id = Column('kms_key_id', Text, nullable=True)
    server_name = Column('server_name', Text, nullable=True)
    service_access_role_arn = Column('service_access_role_arn', Text, nullable=True)
    ssl_mode = Column('ssl_mode', Text, nullable=True)
    status = Column('status', Text, nullable=True)
    username = Column('username', Text, nullable=True)
    endpoint_identifier = Column('endpoint_identifier', Text, nullable=True)
    region = Column('region', Text, nullable=True)
    title = Column('title', Text, nullable=True)
    account_id = Column('account_id', Text, nullable=True)
    sp_connection_name = Column('sp_connection_name', Text, nullable=True)
    partition = Column('partition', Text, nullable=True)