from sqlalchemy import Column
from sqlalchemy.types import JSON, Text, Boolean, TIMESTAMP, BigInteger
from sqlalchemy.dialects import postgresql as psql
from steampipe_alchemy.mixins import FormatMixins

from steampipe_alchemy import Base

class AwsSfnStateMachineExecutionHistory(Base, FormatMixins):
    __tablename__ = 'aws_sfn_state_machine_execution_history'
    task_submitted_event_details = Column('task_submitted_event_details', JSON, nullable=True)
    task_scheduled_event_details = Column('task_scheduled_event_details', JSON, nullable=True)
    task_start_failed_event_details = Column('task_start_failed_event_details', JSON, nullable=True)
    task_started_event_details = Column('task_started_event_details', JSON, nullable=True)
    task_submit_failed_event_details = Column('task_submit_failed_event_details', JSON, nullable=True)
    task_succeeded_event_details = Column('task_succeeded_event_details', JSON, nullable=True)
    task_timed_out_event_details = Column('task_timed_out_event_details', JSON, nullable=True)
    akas = Column('akas', JSON, nullable=True)
    sp_ctx = Column('sp_ctx', JSON, nullable=True)
    _ctx = Column('_ctx', JSON, nullable=True)
    timestamp = Column('timestamp', TIMESTAMP, nullable=True)
    activity_failed_event_details = Column('activity_failed_event_details', JSON, nullable=True)
    activity_schedule_failed_event_details = Column('activity_schedule_failed_event_details', JSON, nullable=True)
    activity_scheduled_event_details = Column('activity_scheduled_event_details', JSON, nullable=True)
    activity_started_event_details = Column('activity_started_event_details', JSON, nullable=True)
    activity_succeeded_event_details = Column('activity_succeeded_event_details', JSON, nullable=True)
    activity_timed_out_event_details = Column('activity_timed_out_event_details', JSON, nullable=True)
    execution_aborted_event_details = Column('execution_aborted_event_details', JSON, nullable=True)
    execution_failed_event_details = Column('execution_failed_event_details', JSON, nullable=True)
    execution_started_event_details = Column('execution_started_event_details', JSON, nullable=True)
    execution_succeeded_event_details = Column('execution_succeeded_event_details', JSON, nullable=True)
    execution_timed_out_event_details = Column('execution_timed_out_event_details', JSON, nullable=True)
    lambda_function_failed_event_details = Column('lambda_function_failed_event_details', JSON, nullable=True)
    lambda_function_schedule_failed_event_details = Column('lambda_function_schedule_failed_event_details', JSON, nullable=True)
    lambda_function_scheduled_event_details = Column('lambda_function_scheduled_event_details', JSON, nullable=True)
    lambda_function_start_failed_event_details = Column('lambda_function_start_failed_event_details', JSON, nullable=True)
    lambda_function_succeeded_event_details = Column('lambda_function_succeeded_event_details', JSON, nullable=True)
    lambda_function_timed_out_event_details = Column('lambda_function_timed_out_event_details', JSON, nullable=True)
    map_iteration_aborted_event_details = Column('map_iteration_aborted_event_details', JSON, nullable=True)
    map_iteration_failed_event_details = Column('map_iteration_failed_event_details', JSON, nullable=True)
    map_iteration_started_event_details = Column('map_iteration_started_event_details', JSON, nullable=True)
    map_iteration_succeeded_event_details = Column('map_iteration_succeeded_event_details', JSON, nullable=True)
    map_state_started_event_details = Column('map_state_started_event_details', JSON, nullable=True)
    state_entered_event_details = Column('state_entered_event_details', JSON, nullable=True)
    state_exited_event_details = Column('state_exited_event_details', JSON, nullable=True)
    task_failed_event_details = Column('task_failed_event_details', JSON, nullable=True)
    execution_arn = Column('execution_arn', Text, nullable=True)
    previous_event_id = Column('previous_event_id', Text, nullable=True)
    id = Column('id', Text, primary_key=True, nullable=True)
    type = Column('type', Text, nullable=True)
    region = Column('region', Text, nullable=True)
    account_id = Column('account_id', Text, nullable=True)
    title = Column('title', Text, nullable=True)
    sp_connection_name = Column('sp_connection_name', Text, nullable=True)
    partition = Column('partition', Text, nullable=True)