from sqlalchemy import Column
from sqlalchemy.types import JSON, Text, Boolean, TIMESTAMP, BigInteger
from sqlalchemy.dialects import postgresql as psql

from steampipe_alchemy.base import Base

class AwsEc2Instance(Base):
    __tablename__ = 'aws_ec2_instance'
    instance_id = Column(Text, name='instance_id', nullable=True)
    instance_type = Column(Text, name='instance_type', nullable=True)
    instance_state = Column(Text, name='instance_state', nullable=True)
    monitoring_state = Column(Text, name='monitoring_state', nullable=True)
    disable_api_termination = Column(Boolean, name='disable_api_termination', nullable=True)
    cpu_options_core_count = Column(BigInteger, name='cpu_options_core_count', nullable=True)
    cpu_options_threads_per_core = Column(BigInteger, name='cpu_options_threads_per_core', nullable=True)
    ebs_optimized = Column(Boolean, name='ebs_optimized', nullable=True)
    hypervisor = Column(Text, name='hypervisor', nullable=True)
    iam_instance_profile_arn = Column(Text, name='iam_instance_profile_arn', nullable=True)
    iam_instance_profile_id = Column(Text, name='iam_instance_profile_id', nullable=True)
    image_id = Column(Text, name='image_id', nullable=True)
    instance_initiated_shutdown_behavior = Column(Text, name='instance_initiated_shutdown_behavior', nullable=True)
    kernel_id = Column(Text, name='kernel_id', nullable=True)
    key_name = Column(Text, name='key_name', nullable=True)
    launch_time = Column(TIMESTAMP, name='launch_time', nullable=True)
    metadata_options = Column(JSON, name='metadata_options', nullable=True)
    outpost_arn = Column(Text, name='outpost_arn', nullable=True)
    placement_availability_zone = Column(Text, name='placement_availability_zone', nullable=True)
    placement_group_name = Column(Text, name='placement_group_name', nullable=True)
    placement_tenancy = Column(Text, name='placement_tenancy', nullable=True)
    private_ip_address = Column(psql.INET, name='private_ip_address', nullable=True)
    private_dns_name = Column(Text, name='private_dns_name', nullable=True)
    public_dns_name = Column(Text, name='public_dns_name', nullable=True)
    public_ip_address = Column(psql.INET, name='public_ip_address', nullable=True)
    ram_disk_id = Column(Text, name='ram_disk_id', nullable=True)
    root_device_name = Column(Text, name='root_device_name', nullable=True)
    root_device_type = Column(Text, name='root_device_type', nullable=True)
    source_dest_check = Column(Boolean, name='source_dest_check', nullable=True)
    sriov_net_support = Column(Text, name='sriov_net_support', nullable=True)
    state_code = Column(BigInteger, name='state_code', nullable=True)
    subnet_id = Column(Text, name='subnet_id', nullable=True)
    user_data = Column(Text, name='user_data', nullable=True)
    virtualization_type = Column(Text, name='virtualization_type', nullable=True)
    vpc_id = Column(Text, name='vpc_id', nullable=True)
    elastic_gpu_associations = Column(JSON, name='elastic_gpu_associations', nullable=True)
    elastic_inference_accelerator_associations = Column(JSON, name='elastic_inference_accelerator_associations', nullable=True)
    block_device_mappings = Column(JSON, name='block_device_mappings', nullable=True)
    network_interfaces = Column(JSON, name='network_interfaces', nullable=True)
    product_codes = Column(JSON, name='product_codes', nullable=True)
    security_groups = Column(JSON, name='security_groups', nullable=True)
    instance_status = Column(JSON, name='instance_status', nullable=True)
    tags_src = Column(JSON, name='tags_src', nullable=True)
    tags = Column(JSON, name='tags', nullable=True)
    title = Column(Text, name='title', primary_key=True, nullable=True)
    akas = Column(JSON, name='akas', nullable=True)
    partition = Column(Text, name='partition', nullable=True)
    region = Column(Text, name='region', nullable=True)
    account_id = Column(Text, name='account_id', nullable=True)