from sqlalchemy import Column
from sqlalchemy.types import JSON, Text, Boolean, TIMESTAMP, BigInteger
from sqlalchemy.dialects import postgresql as psql

from steampipe_alchemy.base import Base

class AwsRdsDbCluster(Base):
    __tablename__ = 'aws_rds_db_cluster'
    db_cluster_identifier = Column(Text, name='db_cluster_identifier', nullable=True)
    arn = Column(Text, name='arn', primary_key=True, nullable=True)
    status = Column(Text, name='status', nullable=True)
    resource_id = Column(Text, name='resource_id', nullable=True)
    create_time = Column(TIMESTAMP, name='create_time', nullable=True)
    activity_stream_kinesis_stream_name = Column(Text, name='activity_stream_kinesis_stream_name', nullable=True)
    activity_stream_kms_key_id = Column(Text, name='activity_stream_kms_key_id', nullable=True)
    activity_stream_mode = Column(Text, name='activity_stream_mode', nullable=True)
    activity_stream_status = Column(Text, name='activity_stream_status', nullable=True)
    allocated_storage = Column(BigInteger, name='allocated_storage', nullable=True)
    backtrack_consumed_change_records = Column(BigInteger, name='backtrack_consumed_change_records', nullable=True)
    backtrack_window = Column(BigInteger, name='backtrack_window', nullable=True)
    backup_retention_period = Column(BigInteger, name='backup_retention_period', nullable=True)
    capacity = Column(BigInteger, name='capacity', nullable=True)
    character_set_name = Column(Text, name='character_set_name', nullable=True)
    clone_group_id = Column(Text, name='clone_group_id', nullable=True)
    copy_tags_to_snapshot = Column(Boolean, name='copy_tags_to_snapshot', nullable=True)
    cross_account_clone = Column(Boolean, name='cross_account_clone', nullable=True)
    database_name = Column(Text, name='database_name', nullable=True)
    db_cluster_parameter_group = Column(Text, name='db_cluster_parameter_group', nullable=True)
    db_subnet_group = Column(Text, name='db_subnet_group', nullable=True)
    deletion_protection = Column(Boolean, name='deletion_protection', nullable=True)
    earliest_backtrack_time = Column(TIMESTAMP, name='earliest_backtrack_time', nullable=True)
    earliest_restorable_time = Column(TIMESTAMP, name='earliest_restorable_time', nullable=True)
    endpoint = Column(Text, name='endpoint', nullable=True)
    engine = Column(Text, name='engine', nullable=True)
    engine_mode = Column(Text, name='engine_mode', nullable=True)
    engine_version = Column(Text, name='engine_version', nullable=True)
    global_write_forwarding_requested = Column(Boolean, name='global_write_forwarding_requested', nullable=True)
    global_write_forwarding_status = Column(Text, name='global_write_forwarding_status', nullable=True)
    hosted_zone_id = Column(Text, name='hosted_zone_id', nullable=True)
    http_endpoint_enabled = Column(Boolean, name='http_endpoint_enabled', nullable=True)
    iam_database_authentication_enabled = Column(Boolean, name='iam_database_authentication_enabled', nullable=True)
    kms_key_id = Column(Text, name='kms_key_id', nullable=True)
    latest_restorable_time = Column(TIMESTAMP, name='latest_restorable_time', nullable=True)
    master_user_name = Column(Text, name='master_user_name', nullable=True)
    multi_az = Column(Boolean, name='multi_az', nullable=True)
    percent_progress = Column(Text, name='percent_progress', nullable=True)
    port = Column(BigInteger, name='port', nullable=True)
    preferred_backup_window = Column(Text, name='preferred_backup_window', nullable=True)
    preferred_maintenance_window = Column(Text, name='preferred_maintenance_window', nullable=True)
    reader_endpoint = Column(Text, name='reader_endpoint', nullable=True)
    storage_encrypted = Column(Boolean, name='storage_encrypted', nullable=True)
    associated_roles = Column(JSON, name='associated_roles', nullable=True)
    availability_zones = Column(JSON, name='availability_zones', nullable=True)
    custom_endpoints = Column(JSON, name='custom_endpoints', nullable=True)
    members = Column(JSON, name='members', nullable=True)
    option_group_memberships = Column(JSON, name='option_group_memberships', nullable=True)
    domain_memberships = Column(JSON, name='domain_memberships', nullable=True)
    enabled_cloudwatch_logs_exports = Column(JSON, name='enabled_cloudwatch_logs_exports', nullable=True)
    read_replica_identifiers = Column(JSON, name='read_replica_identifiers', nullable=True)
    vpc_security_groups = Column(JSON, name='vpc_security_groups', nullable=True)
    tags_src = Column(JSON, name='tags_src', nullable=True)
    tags = Column(JSON, name='tags', nullable=True)
    title = Column(Text, name='title', nullable=True)
    akas = Column(JSON, name='akas', nullable=True)
    partition = Column(Text, name='partition', nullable=True)
    region = Column(Text, name='region', nullable=True)
    account_id = Column(Text, name='account_id', nullable=True)