from sqlalchemy import Column
from sqlalchemy.types import JSON, Text, Boolean, TIMESTAMP, BigInteger
from sqlalchemy.dialects import postgresql as psql
from steampipe_alchemy.mixins import FormatMixins

from steampipe_alchemy import Base

class AwsS3Object(Base, FormatMixins):
    __tablename__ = 'aws_s3_object'
    _ctx = Column('_ctx', JSON, nullable=True)
    last_modified = Column('last_modified', TIMESTAMP, nullable=True)
    bucket_key_enabled = Column('bucket_key_enabled', Boolean, nullable=True)
    delete_marker = Column('delete_marker', Boolean, nullable=True)
    expires = Column('expires', TIMESTAMP, nullable=True)
    object_lock_retain_until_date = Column('object_lock_retain_until_date', TIMESTAMP, nullable=True)
    size = Column('size', BigInteger, nullable=True)
    acl = Column('acl', JSON, nullable=True)
    checksum = Column('checksum', JSON, nullable=True)
    _metadata = Column('_metadata', JSON, nullable=True)
    object_parts = Column('object_parts', JSON, nullable=True)
    owner = Column('owner', JSON, nullable=True)
    tags_src = Column('tags_src', JSON, nullable=True)
    tags = Column('tags', JSON, nullable=True)
    akas = Column('akas', JSON, nullable=True)
    sp_ctx = Column('sp_ctx', JSON, nullable=True)
    content_language = Column('content_language', Text, nullable=True)
    content_length = Column('content_length', Text, nullable=True)
    content_range = Column('content_range', Text, nullable=True)
    content_type = Column('content_type', Text, nullable=True)
    key = Column('key', Text, nullable=True)
    expiration = Column('expiration', Text, nullable=True)
    region = Column('region', Text, nullable=True)
    etag = Column('etag', Text, nullable=True)
    object_lock_legal_hold_status = Column('object_lock_legal_hold_status', Text, nullable=True)
    object_lock_mode = Column('object_lock_mode', Text, nullable=True)
    partition = Column('partition', Text, nullable=True)
    prefix = Column('prefix', Text, nullable=True)
    replication_status = Column('replication_status', Text, nullable=True)
    request_charged = Column('request_charged', Text, nullable=True)
    restore = Column('restore', Text, nullable=True)
    server_side_encryption = Column('server_side_encryption', Text, nullable=True)
    account_id = Column('account_id', Text, nullable=True)
    sse_customer_algorithm = Column('sse_customer_algorithm', Text, nullable=True)
    sse_customer_key_md5 = Column('sse_customer_key_md5', Text, nullable=True)
    sse_kms_key_id = Column('sse_kms_key_id', Text, nullable=True)
    tag_count = Column('tag_count', Text, nullable=True)
    website_redirection_location = Column('website_redirection_location', Text, nullable=True)
    arn = Column('arn', Text, primary_key=True, nullable=True)
    bucket_name = Column('bucket_name', Text, nullable=True)
    sp_connection_name = Column('sp_connection_name', Text, nullable=True)
    storage_class = Column('storage_class', Text, nullable=True)
    version_id = Column('version_id', Text, nullable=True)
    accept_ranges = Column('accept_ranges', Text, nullable=True)
    body = Column('body', Text, nullable=True)
    title = Column('title', Text, nullable=True)
    cache_control = Column('cache_control', Text, nullable=True)
    checksum_crc32 = Column('checksum_crc32', Text, nullable=True)
    checksum_crc32c = Column('checksum_crc32c', Text, nullable=True)
    checksum_sha1 = Column('checksum_sha1', Text, nullable=True)
    checksum_sha256 = Column('checksum_sha256', Text, nullable=True)
    content_disposition = Column('content_disposition', Text, nullable=True)
    content_encoding = Column('content_encoding', Text, nullable=True)
