from sqlalchemy import Column
from sqlalchemy.types import JSON, Text, Boolean, TIMESTAMP, BigInteger
from sqlalchemy.dialects import postgresql as psql
from steampipe_alchemy.mixins import FormatMixins

from steampipe_alchemy import Base

class AwsSsmInventory(Base, FormatMixins):
    __tablename__ = 'aws_ssm_inventory'
    schema = Column('schema', JSON, nullable=True)
    capture_time = Column('capture_time', TIMESTAMP, nullable=True)
    content = Column('content', JSON, nullable=True)
    sp_ctx = Column('sp_ctx', JSON, nullable=True)
    _ctx = Column('_ctx', JSON, nullable=True)
    component_attribute_value = Column('component_attribute_value', Text, nullable=True)
    application_attribute_key = Column('application_attribute_key', Text, nullable=True)
    application_attribute_value = Column('application_attribute_value', Text, nullable=True)
    compliance_attribute_key = Column('compliance_attribute_key', Text, nullable=True)
    compliance_attribute_value = Column('compliance_attribute_value', Text, nullable=True)
    file_attribute_key = Column('file_attribute_key', Text, nullable=True)
    file_attribute_value = Column('file_attribute_value', Text, nullable=True)
    instance_detailed_information_attribute_key = Column('instance_detailed_information_attribute_key', Text, nullable=True)
    instance_detailed_information_attribute_value = Column('instance_detailed_information_attribute_value', Text, nullable=True)
    instance_information_attribute_key = Column('instance_information_attribute_key', Text, nullable=True)
    instance_information_attribute_value = Column('instance_information_attribute_value', Text, nullable=True)
    network_attribute_key = Column('network_attribute_key', Text, nullable=True)
    network_attribute_value = Column('network_attribute_value', Text, nullable=True)
    windows_registry_attribute_key = Column('windows_registry_attribute_key', Text, nullable=True)
    windows_registry_attribute_value = Column('windows_registry_attribute_value', Text, nullable=True)
    patch_compliance_attribute_key = Column('patch_compliance_attribute_key', Text, nullable=True)
    patch_compliance_attribute_value = Column('patch_compliance_attribute_value', Text, nullable=True)
    patch_summary_attribute_key = Column('patch_summary_attribute_key', Text, nullable=True)
    patch_summary_attribute_value = Column('patch_summary_attribute_value', Text, nullable=True)
    resource_group_attribute_key = Column('resource_group_attribute_key', Text, nullable=True)
    resource_group_attribute_value = Column('resource_group_attribute_value', Text, nullable=True)
    service_attribute_key = Column('service_attribute_key', Text, nullable=True)
    id = Column('id', Text, primary_key=True, nullable=True)
    tag_attribute_key = Column('tag_attribute_key', Text, nullable=True)
    tag_attribute_value = Column('tag_attribute_value', Text, nullable=True)
    windows_role_attribute_key = Column('windows_role_attribute_key', Text, nullable=True)
    windows_role_attribute_value = Column('windows_role_attribute_value', Text, nullable=True)
    windows_update_attribute_key = Column('windows_update_attribute_key', Text, nullable=True)
    windows_update_attribute_value = Column('windows_update_attribute_value', Text, nullable=True)
    schema_version = Column('schema_version', Text, nullable=True)
    title = Column('title', Text, nullable=True)
    partition = Column('partition', Text, nullable=True)
    region = Column('region', Text, nullable=True)
    account_id = Column('account_id', Text, nullable=True)
    sp_connection_name = Column('sp_connection_name', Text, nullable=True)
    service_attribute_value = Column('service_attribute_value', Text, nullable=True)
    type_name = Column('type_name', Text, nullable=True)
    filter_key = Column('filter_key', Text, nullable=True)
    filter_value = Column('filter_value', Text, nullable=True)
    component_attribute_key = Column('component_attribute_key', Text, nullable=True)